/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('de' | 'en' | 'fr' | 'pt' | 'es' | 'tr' | 'sq' | 'ru' | 'el' | 'ar' | 'zh')
    | ('de' | 'en' | 'fr' | 'pt' | 'es' | 'tr' | 'sq' | 'ru' | 'el' | 'ar' | 'zh')[];
  globals: {
    navigation: Navigation;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'de' | 'en' | 'fr' | 'pt' | 'es' | 'tr' | 'sq' | 'ru' | 'el' | 'ar' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        eyebrow?: string | null;
        heading: string;
        highlight?: string | null;
        description?: string | null;
        image?: (number | null) | Media;
        actions?:
          | {
              label: string;
              url: string;
              style?: ('primary' | 'secondary' | 'link') | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        heading?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        width?: ('narrow' | 'normal' | 'wide') | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'content';
      }
    | {
        media: number | Media;
        caption?: string | null;
        fullWidth?: boolean | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'media';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        items?:
          | {
              title: string;
              description?: string | null;
              /**
               * Lucide-Iconname, z. B. Globe, Palette oder Code2
               */
              icon?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGrid';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        /**
         * Leer lassen, um alle veröffentlichten Projekte zu zeigen.
         */
        selection?: (number | Project)[] | null;
        showFilters?: boolean | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'projects';
      }
    | {
        items?:
          | {
              value: string;
              label: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        heading: string;
        items?:
          | {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[]
          | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading: string;
        description?: string | null;
        actions?:
          | {
              label: string;
              url: string;
              style?: ('primary' | 'secondary' | 'link') | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        eyebrow?: string | null;
        heading: string;
        description?: string | null;
        recipientEmail: string;
        showForm?: boolean | null;
        settings?: {
          /**
           * Optional, z. B. leistungen oder kontakt
           */
          anchor?: string | null;
          theme?: ('default' | 'dark' | 'light' | 'accent') | null;
          spacing?: ('compact' | 'normal' | 'large') | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
  )[];
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  description: string;
  url: string;
  thumbnail?: (number | null) | Media;
  category: 'web' | 'design' | 'showcase' | 'social' | 'ecommerce' | 'nonprofit' | 'gastro';
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  projectStatus?: ('showcase' | 'development' | 'live') | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              highlight?: T;
              description?: T;
              image?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    newTab?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              width?: T;
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              caption?: T;
              fullWidth?: T;
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              selection?: T;
              showFilters?: T;
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              actions?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    newTab?: T;
                    id?: T;
                  };
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              description?: T;
              recipientEmail?: T;
              showForm?: T;
              settings?:
                | T
                | {
                    anchor?: T;
                    theme?: T;
                    spacing?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  url?: T;
  thumbnail?: T;
  category?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  projectStatus?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  items?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  claim?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  defaultSEOImage?: (number | null) | Media;
  contactEmail?: string | null;
  phone?: string | null;
  address?: string | null;
  cookieNotice?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  items?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  claim?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultSEOImage?: T;
  contactEmail?: T;
  phone?: T;
  address?: T;
  cookieNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}