import type { Language } from './language'
import { japaneseAttachmentCopy } from './japanese-copy'

const en = {
  attachments: 'Attachments', chooseFiles: 'Choose files', attachmentHelp: 'Images, PDFs and videos. Up to 5 files per request, 20 MB per file.',
  removeFile: 'Remove file', submittedFiles: 'Submitted files', uploadingFiles: 'Uploading files …',
  attachmentTooLarge: 'Each file must be between 1 byte and 20 MB.', attachmentInvalidType: 'Please choose JPG, PNG, WebP, GIF, PDF, MP4 or WebM files.',
  attachmentTooMany: 'Choose up to 5 files per request. A project can have up to 20 attachments.', attachmentUploadError: 'The files could not be uploaded. Your draft is still here; please try again.',
}
type AttachmentCopy = Record<keyof typeof en, string>
export const attachmentCopy: Record<Language, AttachmentCopy> = {
  ja: japaneseAttachmentCopy,
  en,
  de: { attachments: 'Anhänge', chooseFiles: 'Dateien auswählen', attachmentHelp: 'Bilder, PDFs und Videos. Bis zu 5 Dateien pro Anfrage, jeweils maximal 20 MB.', removeFile: 'Datei entfernen', submittedFiles: 'Eingereichte Dateien', uploadingFiles: 'Dateien werden hochgeladen …', attachmentTooLarge: 'Jede Datei muss zwischen 1 Byte und 20 MB groß sein.', attachmentInvalidType: 'Bitte JPG, PNG, WebP, GIF, PDF, MP4 oder WebM auswählen.', attachmentTooMany: 'Bis zu 5 Dateien pro Anfrage auswählen. Ein Projekt kann bis zu 20 Anhänge enthalten.', attachmentUploadError: 'Die Dateien konnten nicht hochgeladen werden. Ihr Entwurf ist noch vorhanden; bitte versuchen Sie es erneut.' },
  fr: { attachments: 'Pièces jointes', chooseFiles: 'Choisir des fichiers', attachmentHelp: 'Images, PDF et vidéos. Jusqu’à 5 fichiers par demande, 20 Mo par fichier.', removeFile: 'Retirer le fichier', submittedFiles: 'Fichiers envoyés', uploadingFiles: 'Envoi des fichiers …', attachmentTooLarge: 'Chaque fichier doit avoir une taille comprise entre 1 octet et 20 Mo.', attachmentInvalidType: 'Choisissez des fichiers JPG, PNG, WebP, GIF, PDF, MP4 ou WebM.', attachmentTooMany: 'Jusqu’à 5 fichiers par demande et 20 pièces jointes par projet.', attachmentUploadError: 'L’envoi a échoué. Votre brouillon est conservé ; veuillez réessayer.' },
  ar: { attachments: 'المرفقات', chooseFiles: 'اختيار الملفات', attachmentHelp: 'صور وملفات PDF وفيديو. حتى 5 ملفات لكل طلب، بحد أقصى 20 ميغابايت لكل ملف.', removeFile: 'إزالة الملف', submittedFiles: 'الملفات المرسلة', uploadingFiles: 'جارٍ رفع الملفات …', attachmentTooLarge: 'يجب أن يكون حجم كل ملف بين بايت واحد و20 ميغابايت.', attachmentInvalidType: 'يرجى اختيار ملفات JPG أو PNG أو WebP أو GIF أو PDF أو MP4 أو WebM.', attachmentTooMany: 'حتى 5 ملفات لكل طلب و20 مرفقًا لكل مشروع.', attachmentUploadError: 'تعذّر رفع الملفات. مسودتك محفوظة؛ يرجى المحاولة مرة أخرى.' },
  th: { attachments: 'ไฟล์แนบ', chooseFiles: 'เลือกไฟล์', attachmentHelp: 'รูปภาพ PDF และวิดีโอ สูงสุด 5 ไฟล์ต่อคำขอ และ 20 MB ต่อไฟล์', removeFile: 'นำไฟล์ออก', submittedFiles: 'ไฟล์ที่ส่งแล้ว', uploadingFiles: 'กำลังอัปโหลดไฟล์ …', attachmentTooLarge: 'แต่ละไฟล์ต้องมีขนาดตั้งแต่ 1 ไบต์ถึง 20 MB', attachmentInvalidType: 'โปรดเลือกไฟล์ JPG, PNG, WebP, GIF, PDF, MP4 หรือ WebM', attachmentTooMany: 'สูงสุด 5 ไฟล์ต่อคำขอ และ 20 ไฟล์แนบต่อโครงการ', attachmentUploadError: 'อัปโหลดไฟล์ไม่สำเร็จ ร่างของคุณยังอยู่ โปรดลองอีกครั้ง' },
  hi: { attachments: 'संलग्न फ़ाइलें', chooseFiles: 'फ़ाइलें चुनें', attachmentHelp: 'चित्र, PDF और वीडियो। प्रति अनुरोध अधिकतम 5 फ़ाइलें, प्रत्येक 20 MB तक।', removeFile: 'फ़ाइल हटाएँ', submittedFiles: 'भेजी गई फ़ाइलें', uploadingFiles: 'फ़ाइलें अपलोड हो रही हैं …', attachmentTooLarge: 'हर फ़ाइल का आकार 1 बाइट से 20 MB के बीच होना चाहिए।', attachmentInvalidType: 'JPG, PNG, WebP, GIF, PDF, MP4 या WebM फ़ाइलें चुनें।', attachmentTooMany: 'प्रति अनुरोध 5 फ़ाइलें और प्रति प्रोजेक्ट 20 संलग्न फ़ाइलें तक।', attachmentUploadError: 'फ़ाइलें अपलोड नहीं हुईं। आपका मसौदा सुरक्षित है; फिर कोशिश करें।' },
  tr: { attachments: 'Ekler', chooseFiles: 'Dosya seç', attachmentHelp: 'Görseller, PDF ve videolar. Talep başına 5 dosya, dosya başına en fazla 20 MB.', removeFile: 'Dosyayı kaldır', submittedFiles: 'Gönderilen dosyalar', uploadingFiles: 'Dosyalar yükleniyor …', attachmentTooLarge: 'Her dosya 1 bayt ile 20 MB arasında olmalıdır.', attachmentInvalidType: 'JPG, PNG, WebP, GIF, PDF, MP4 veya WebM dosyaları seçin.', attachmentTooMany: 'Talep başına 5 dosya, proje başına 20 ek sınırı vardır.', attachmentUploadError: 'Dosyalar yüklenemedi. Taslağınız duruyor; lütfen tekrar deneyin.' },
  sq: { attachments: 'Bashkëngjitje', chooseFiles: 'Zgjidhni skedarët', attachmentHelp: 'Imazhe, PDF dhe video. Deri në 5 skedarë për kërkesë, 20 MB për skedar.', removeFile: 'Hiq skedarin', submittedFiles: 'Skedarët e dërguar', uploadingFiles: 'Duke ngarkuar skedarët …', attachmentTooLarge: 'Çdo skedar duhet të jetë nga 1 bajt deri në 20 MB.', attachmentInvalidType: 'Zgjidhni skedarë JPG, PNG, WebP, GIF, PDF, MP4 ose WebM.', attachmentTooMany: 'Deri në 5 skedarë për kërkesë dhe 20 bashkëngjitje për projekt.', attachmentUploadError: 'Skedarët nuk u ngarkuan. Drafti juaj është ruajtur; provoni përsëri.' },
  ru: { attachments: 'Вложения', chooseFiles: 'Выбрать файлы', attachmentHelp: 'Изображения, PDF и видео. До 5 файлов на запрос, до 20 МБ на файл.', removeFile: 'Убрать файл', submittedFiles: 'Отправленные файлы', uploadingFiles: 'Загрузка файлов …', attachmentTooLarge: 'Размер каждого файла должен быть от 1 байта до 20 МБ.', attachmentInvalidType: 'Выберите файлы JPG, PNG, WebP, GIF, PDF, MP4 или WebM.', attachmentTooMany: 'До 5 файлов на запрос и 20 вложений на проект.', attachmentUploadError: 'Не удалось загрузить файлы. Черновик сохранён; попробуйте ещё раз.' },
  es: { attachments: 'Archivos adjuntos', chooseFiles: 'Elegir archivos', attachmentHelp: 'Imágenes, PDF y vídeos. Hasta 5 archivos por solicitud, 20 MB por archivo.', removeFile: 'Quitar archivo', submittedFiles: 'Archivos enviados', uploadingFiles: 'Subiendo archivos …', attachmentTooLarge: 'Cada archivo debe tener entre 1 byte y 20 MB.', attachmentInvalidType: 'Elija archivos JPG, PNG, WebP, GIF, PDF, MP4 o WebM.', attachmentTooMany: 'Hasta 5 archivos por solicitud y 20 adjuntos por proyecto.', attachmentUploadError: 'No se pudieron subir los archivos. Su borrador sigue aquí; inténtelo de nuevo.' },
  it: { attachments: 'Allegati', chooseFiles: 'Scegli file', attachmentHelp: 'Immagini, PDF e video. Fino a 5 file per richiesta, 20 MB per file.', removeFile: 'Rimuovi file', submittedFiles: 'File inviati', uploadingFiles: 'Caricamento dei file …', attachmentTooLarge: 'Ogni file deve avere una dimensione tra 1 byte e 20 MB.', attachmentInvalidType: 'Scegli file JPG, PNG, WebP, GIF, PDF, MP4 o WebM.', attachmentTooMany: 'Fino a 5 file per richiesta e 20 allegati per progetto.', attachmentUploadError: 'Caricamento non riuscito. La bozza è conservata; riprovi.' },
  uk: { attachments: 'Вкладення', chooseFiles: 'Вибрати файли', attachmentHelp: 'Зображення, PDF та відео. До 5 файлів на запит, до 20 МБ на файл.', removeFile: 'Прибрати файл', submittedFiles: 'Надіслані файли', uploadingFiles: 'Завантаження файлів …', attachmentTooLarge: 'Розмір кожного файлу має бути від 1 байта до 20 МБ.', attachmentInvalidType: 'Виберіть файли JPG, PNG, WebP, GIF, PDF, MP4 або WebM.', attachmentTooMany: 'До 5 файлів на запит і 20 вкладень на проєкт.', attachmentUploadError: 'Не вдалося завантажити файли. Чернетку збережено; спробуйте ще раз.' },
  el: { attachments: 'Συνημμένα', chooseFiles: 'Επιλογή αρχείων', attachmentHelp: 'Εικόνες, PDF και βίντεο. Έως 5 αρχεία ανά αίτημα, 20 MB ανά αρχείο.', removeFile: 'Αφαίρεση αρχείου', submittedFiles: 'Απεσταλμένα αρχεία', uploadingFiles: 'Μεταφόρτωση αρχείων …', attachmentTooLarge: 'Κάθε αρχείο πρέπει να είναι από 1 byte έως 20 MB.', attachmentInvalidType: 'Επιλέξτε αρχεία JPG, PNG, WebP, GIF, PDF, MP4 ή WebM.', attachmentTooMany: 'Έως 5 αρχεία ανά αίτημα και 20 συνημμένα ανά έργο.', attachmentUploadError: 'Η μεταφόρτωση απέτυχε. Το πρόχειρό σας διατηρείται· δοκιμάστε ξανά.' },
  pt: { attachments: 'Anexos', chooseFiles: 'Escolher ficheiros', attachmentHelp: 'Imagens, PDF e vídeos. Até 5 ficheiros por pedido, 20 MB por ficheiro.', removeFile: 'Remover ficheiro', submittedFiles: 'Ficheiros enviados', uploadingFiles: 'A carregar ficheiros …', attachmentTooLarge: 'Cada ficheiro deve ter entre 1 byte e 20 MB.', attachmentInvalidType: 'Escolha ficheiros JPG, PNG, WebP, GIF, PDF, MP4 ou WebM.', attachmentTooMany: 'Até 5 ficheiros por pedido e 20 anexos por projeto.', attachmentUploadError: 'Não foi possível carregar os ficheiros. O rascunho está guardado; tente novamente.' },
  zh: { attachments: '附件', chooseFiles: '选择文件', attachmentHelp: '图片、PDF 和视频。每次请求最多 5 个文件，每个文件不超过 20 MB。', removeFile: '移除文件', submittedFiles: '已提交的文件', uploadingFiles: '正在上传文件 …', attachmentTooLarge: '每个文件大小必须在 1 字节到 20 MB 之间。', attachmentInvalidType: '请选择 JPG、PNG、WebP、GIF、PDF、MP4 或 WebM 文件。', attachmentTooMany: '每次请求最多 5 个文件，每个项目最多 20 个附件。', attachmentUploadError: '文件上传失败。您的草稿仍然保留，请重试。' },
}
