export const hindiCopy: Record<string, string> = {
  "nav.services": "सेवाएँ",
  "nav.projects": "प्रोजेक्ट",
  "nav.vision": "काम करने का तरीका",
  "nav.contact": "संपर्क",
  "language.select": "भाषा चुनें",
  "hero.badge": "2026 में स्थापित",
  "hero.subtitle": "हम सोचते, डिज़ाइन करते और विकसित करते हैं",
  "hero.title2": "जो पहचान बढ़ाएँ और बिक्री में मदद करें।",
  "hero.cta": "प्रोजेक्ट शुरू करें",
  "hero.cta2": "निःशुल्क शुरुआती परामर्श",
  "hero.vision": "हमारी दृष्टि",
  "hero.languages": "जर्मन और अंग्रेज़ी में धाराप्रवाह · अरबी और फ़्रेंच में पेशेवर दक्षता",
  "stats.founded": "स्थापित",
  "stats.potential": "संभावनाएँ",
  "stats.passion": "जुनून",
  "stats.availability": "उपलब्धता",
  "services.label": "सेवाएँ",
  "services.ai.title": "AI की मदद से वीडियो और चित्र संपादन",
  "projects.preview": "लाइव प्रीव्यू उपलब्ध है",
  "projects.viewProject": "प्रोजेक्ट देखें",
  "projects.moreComingSoon": "जल्द ही और प्रोजेक्ट आएँगे...",
  "projects.crypto.title": "क्रिप्टो समाचार पोर्टल",
  "projects.crypto.description": "रीयल-टाइम अपडेट, बाज़ार विश्लेषण और उद्योग की खबरों वाला आधुनिक क्रिप्टो समाचार पोर्टल।",
  "projects.studio.title": "Studio Glacé",
  "projects.studio.description": "रचनात्मक डिज़ाइन स्टूडियो के लिए सरल सौंदर्य और सहज एनिमेशन वाली आकर्षक पोर्टफ़ोलियो वेबसाइट।",
  "projects.joesgarage.title": "Joe's Garage Kassel",
  "projects.joesgarage.description": "कासेल के प्रसिद्ध रॉक बार Joe's Garage के लिए आधुनिक वेबसाइट। बार के असली माहौल के साथ पेय, कार्यक्रम, लाइव संगीत, सामूहिक प्रसारण, गैलरी, खुलने का समय और रास्ते की जानकारी।",
  "projects.luxury.title": "AWD Shop",
  "projects.luxury.description": "आधुनिक डिज़ाइन और सहज उपयोग अनुभव वाला प्रीमियम फ़ैशन ऑनलाइन स्टोर।",
  "projects.donation.title": "Al Salam दान वेबसाइट",
  "projects.donation.description": "मानवीय उद्देश्यों के लिए आधुनिक डिज़ाइन और उपयोग में आसान दान प्रबंधन वाली पेशेवर वेबसाइट।",
  "projects.hazechill.title": "Haze & Chill Cafe",
  "projects.hazechill.description": "कैफ़े के लिए डिज़ाइन और सोशल मीडिया प्रबंधन — ब्रांड पहचान से Instagram तक। इसके साथ मेन्यू डिज़ाइन, विज्ञापन साझेदारों से संवाद और अवधारणा के विकास तथा विस्तार में सहायता।",
  "projects.reel.title": "Haze & Chill Café — सामग्री निर्माण",
  "projects.reel.description": "यह काम Haze & Chill Café के लिए हमारी सामग्री निर्माण प्रक्रिया का हिस्सा है। हम ब्रांड के Instagram के लिए Reels और दृश्य सामग्री बनाते हैं।",
  "tools.badge": "टेक्नोलॉजी स्टैक",
  "contact.label": "संपर्क",
  "contact.email": "ईमेल",
  "contact.phone": "फ़ोन",
  "contact.location": "स्थान",
  "contact.whatsapp": "सीधे WhatsApp पर संपर्क करें",
  "contact.form.name": "नाम *",
  "contact.form.namePlaceholder": "आपका नाम",
  "contact.form.email": "ईमेल *",
  "contact.form.emailPlaceholder": "you@email.com",
  "contact.form.phone": "फ़ोन (वैकल्पिक)",
  "contact.form.phonePlaceholder": "+91 98765 43210",
  "contact.form.message": "संदेश *",
  "contact.form.submit": "संदेश भेजें",
  "contact.form.sending": "भेजा जा रहा है...",
  "footer.imprint": "प्रदाता की जानकारी",
  "footer.privacy": "गोपनीयता",
  "footer.agb": "सेवा की शर्तें",
  "footer.rights": "सर्वाधिकार सुरक्षित।",
  "modal.backToSite": "वेबसाइट पर वापस जाएँ"
}
