import type { Language } from './language'

type LinksCopy = {
  headline: string; intro: string; founder: string; projects: string; projectsIntro: string;
  work: string; social: string; community: string; playlist: string; personal: string; team: string;
}

export const linksCopy: Record<Language, LinksCopy> = {
  de: { headline: 'Alle Links. Ein Kontakt.', intro: 'Meine Projekte, Profile und die direkten Wege, mich zu erreichen – alles an einem Ort.', founder: 'Gründer von Naser Solutions', projects: 'Website & Projekte', projectsIntro: 'Lerne meine Arbeit kennen und entdecke ausgewählte Projekte.', work: 'Ausgewählte Arbeiten', social: 'Social Media', community: 'Kontakt & Community', playlist: 'Meine Musik', personal: 'Yasin Aissani · Persönlich', team: 'Unser Community-Server' },
  en: { headline: 'All my links. One place.', intro: 'My projects, profiles and direct ways to get in touch, all in one place.', founder: 'Founder of Naser Solutions', projects: 'Website & projects', projectsIntro: 'Get to know my work and explore selected projects.', work: 'Selected work', social: 'Social media', community: 'Contact & community', playlist: 'My music', personal: 'Yasin Aissani · Personal', team: 'Our community server' },
  fr: { headline: 'Tous mes liens. Un seul endroit.', intro: 'Mes projets, mes profils et les moyens de me contacter, réunis au même endroit.', founder: 'Fondateur de Naser Solutions', projects: 'Site web et projets', projectsIntro: 'Découvrez mon travail et une sélection de projets.', work: 'Une sélection de réalisations', social: 'Réseaux sociaux', community: 'Contact et communauté', playlist: 'Ma musique', personal: 'Yasin Aissani · Personnel', team: 'Notre serveur communautaire' },
  es: { headline: 'Todos mis enlaces. Un lugar.', intro: 'Mis proyectos, perfiles y formas de contactar conmigo, todo en un solo lugar.', founder: 'Fundador de Naser Solutions', projects: 'Sitio web y proyectos', projectsIntro: 'Conoce mi trabajo y descubre una selección de proyectos.', work: 'Trabajos seleccionados', social: 'Redes sociales', community: 'Contacto y comunidad', playlist: 'Mi música', personal: 'Yasin Aissani · Personal', team: 'Nuestro servidor de comunidad' },
  it: { headline: 'Tutti i miei link. Un solo posto.', intro: 'I miei progetti, profili e modi per contattarmi, tutti in un unico posto.', founder: 'Fondatore di Naser Solutions', projects: 'Sito web e progetti', projectsIntro: 'Scopri il mio lavoro e una selezione di progetti.', work: 'Lavori selezionati', social: 'Social media', community: 'Contatti e community', playlist: 'La mia musica', personal: 'Yasin Aissani · Personale', team: 'Il nostro server della community' },
  pt: { headline: 'Todos os meus links. Um lugar.', intro: 'Meus projetos, perfis e formas de entrar em contato, tudo em um só lugar.', founder: 'Fundador da Naser Solutions', projects: 'Site e projetos', projectsIntro: 'Conheça meu trabalho e explore projetos selecionados.', work: 'Trabalhos selecionados', social: 'Redes sociais', community: 'Contato e comunidade', playlist: 'Minha música', personal: 'Yasin Aissani · Pessoal', team: 'Nosso servidor da comunidade' },
  tr: { headline: 'Tüm bağlantılarım. Tek bir yer.', intro: 'Projelerim, profillerim ve bana ulaşmanın yolları, hepsi tek bir yerde.', founder: 'Naser Solutions kurucusu', projects: 'Web sitesi ve projeler', projectsIntro: 'Çalışmalarımı tanıyın ve seçili projeleri keşfedin.', work: 'Seçili çalışmalar', social: 'Sosyal medya', community: 'İletişim ve topluluk', playlist: 'Müziğim', personal: 'Yasin Aissani · Kişisel', team: 'Topluluk sunucumuz' },
  sq: { headline: 'Të gjitha lidhjet. Në një vend.', intro: 'Projektet, profilet e mia dhe mënyrat për të më kontaktuar, të gjitha në një vend.', founder: 'Themelues i Naser Solutions', projects: 'Faqja dhe projektet', projectsIntro: 'Njih punën time dhe zbulo projekte të përzgjedhura.', work: 'Punë të përzgjedhura', social: 'Rrjetet sociale', community: 'Kontakt dhe komunitet', playlist: 'Muzika ime', personal: 'Yasin Aissani · Personal', team: 'Serveri ynë i komunitetit' },
  ru: { headline: 'Все мои ссылки. В одном месте.', intro: 'Мои проекты, профили и способы связаться со мной — всё в одном месте.', founder: 'Основатель Naser Solutions', projects: 'Сайт и проекты', projectsIntro: 'Познакомьтесь с моей работой и избранными проектами.', work: 'Избранные работы', social: 'Социальные сети', community: 'Контакты и сообщество', playlist: 'Моя музыка', personal: 'Yasin Aissani · Личный профиль', team: 'Сервер нашего сообщества' },
  uk: { headline: 'Усі мої посилання. В одному місці.', intro: 'Мої проєкти, профілі та способи зв’язатися зі мною — усе в одному місці.', founder: 'Засновник Naser Solutions', projects: 'Сайт і проєкти', projectsIntro: 'Познайомтеся з моєю роботою та вибраними проєктами.', work: 'Вибрані роботи', social: 'Соціальні мережі', community: 'Контакти та спільнота', playlist: 'Моя музика', personal: 'Yasin Aissani · Особистий профіль', team: 'Сервер нашої спільноти' },
  el: { headline: 'Όλοι οι σύνδεσμοι. Σε ένα μέρος.', intro: 'Τα έργα μου, τα προφίλ μου και οι τρόποι επικοινωνίας μαζί μου, όλα σε ένα μέρος.', founder: 'Ιδρυτής της Naser Solutions', projects: 'Ιστοσελίδα και έργα', projectsIntro: 'Γνωρίστε τη δουλειά μου και ανακαλύψτε επιλεγμένα έργα.', work: 'Επιλεγμένες δουλειές', social: 'Κοινωνικά δίκτυα', community: 'Επικοινωνία και κοινότητα', playlist: 'Η μουσική μου', personal: 'Yasin Aissani · Προσωπικό', team: 'Ο διακομιστής της κοινότητάς μας' },
  ar: { headline: 'كل روابطي في مكان واحد.', intro: 'مشاريعي وحساباتي وطرق التواصل المباشر معي، كلها في مكان واحد.', founder: 'مؤسس Naser Solutions', projects: 'الموقع والمشاريع', projectsIntro: 'تعرّف على عملي واستكشف مشاريع مختارة.', work: 'أعمال مختارة', social: 'وسائل التواصل الاجتماعي', community: 'التواصل والمجتمع', playlist: 'موسيقاي', personal: 'Yasin Aissani · حساب شخصي', team: 'خادم مجتمعنا' },
  th: { headline: 'ทุกลิงก์ของฉัน ในที่เดียว', intro: 'โปรเจกต์ โปรไฟล์ และช่องทางติดต่อฉันโดยตรง รวมไว้ในที่เดียว', founder: 'ผู้ก่อตั้ง Naser Solutions', projects: 'เว็บไซต์และโปรเจกต์', projectsIntro: 'ทำความรู้จักผลงานของฉันและดูโปรเจกต์ที่คัดสรรมา', work: 'ผลงานที่คัดสรร', social: 'โซเชียลมีเดีย', community: 'ติดต่อและชุมชน', playlist: 'เพลงของฉัน', personal: 'Yasin Aissani · ส่วนตัว', team: 'เซิร์ฟเวอร์ชุมชนของเรา' },
  hi: { headline: 'मेरे सभी लिंक। एक ही जगह।', intro: 'मेरे प्रोजेक्ट, प्रोफ़ाइल और मुझसे सीधे संपर्क करने के तरीके, सभी एक ही जगह।', founder: 'Naser Solutions के संस्थापक', projects: 'वेबसाइट और प्रोजेक्ट', projectsIntro: 'मेरे काम को जानें और चुनिंदा प्रोजेक्ट देखें।', work: 'चुनिंदा काम', social: 'सोशल मीडिया', community: 'संपर्क और समुदाय', playlist: 'मेरा संगीत', personal: 'Yasin Aissani · निजी', team: 'हमारा समुदाय सर्वर' },
  zh: { headline: '所有链接，尽在一处。', intro: '我的项目、个人主页和直接联系方式，都汇集在这里。', founder: 'Naser Solutions 创始人', projects: '网站与项目', projectsIntro: '了解我的工作，浏览精选项目。', work: '精选作品', social: '社交媒体', community: '联系与社区', playlist: '我的音乐', personal: 'Yasin Aissani · 个人主页', team: '我们的社区服务器' },
  ja: { headline: 'すべてのリンクを、ひとつに。', intro: '私のプロジェクト、プロフィール、直接の連絡先を、ここにまとめました。', founder: 'Naser Solutions 創業者', projects: 'ウェブサイト・プロジェクト', projectsIntro: '私の仕事と、これまでの主なプロジェクトをご覧ください。', work: '主な制作実績', social: 'ソーシャルメディア', community: '連絡先・コミュニティ', playlist: '私の音楽', personal: 'Yasin Aissani · 個人アカウント', team: 'コミュニティサーバー' },
}
