import type { Language } from './language'

const de = {
  selectLanguage: 'Sprache auswählen',
  area: 'Ihr Kundenbereich', welcome: 'Willkommen', description: 'Hier finden Sie den aktuellen Stand und die wichtigsten Informationen zu Ihrem Projekt.',
  emptyTitle: 'Noch kein Projekt zugeordnet', emptyDescription: 'Sobald Ihr Projekt freigeschaltet wurde, erscheint es automatisch an dieser Stelle.',
  project: 'Ihr Projekt', domain: 'Domain', openWebsite: 'Website öffnen', support: 'Benötigen Sie direkte Unterstützung? Kontaktieren Sie Ihr Team bei Naser Solutions.',
  feedback: 'Feedback / Änderungswünsche', feedbackPlaceholder: 'Welche Anpassungen wünschen Sie sich?', save: 'Feedback speichern', saving: 'Wird gespeichert …',
  logout: 'Abmelden', loggingOut: 'Abmeldung …', portal: 'Kundenportal', loginDescription: 'Melden Sie sich an, um den aktuellen Stand Ihres Projekts einzusehen.',
  email: 'E-Mail-Adresse', password: 'Passwort', login: 'Sicher anmelden', loggingIn: 'Anmeldung läuft …', restricted: 'Der Zugang ist ausschließlich für autorisierte Kunden bestimmt.',
  invalidLogin: 'E-Mail-Adresse oder Passwort ist nicht korrekt.', networkError: 'Die Verbindung ist fehlgeschlagen. Bitte versuchen Sie es erneut.',
  invalidFeedback: 'Die Eingabe konnte nicht verarbeitet werden.', feedbackTooLong: 'Das Feedback darf maximal 5.000 Zeichen enthalten.',
  sessionExpired: 'Ihre Sitzung ist abgelaufen. Bitte melden Sie sich erneut an.', saved: 'Ihre Änderungswünsche wurden sicher gespeichert.', saveError: 'Das Feedback konnte nicht gespeichert werden.',
  statusPreparation: 'In Vorbereitung', statusActive: 'In Bearbeitung', statusLive: 'Veröffentlicht', statusPaused: 'Pausiert',
}

export type PortalCopy = Record<keyof typeof de, string>
export type FeedbackMessage = 'invalidFeedback' | 'feedbackTooLong' | 'sessionExpired' | 'saved' | 'saveError'

export const portalCopy: Record<Language, PortalCopy> = {
  de,
  en: {
    selectLanguage: 'Select language',
    area: 'Your client area', welcome: 'Welcome', description: 'Find the current progress and key information about your project here.',
    emptyTitle: 'No project assigned yet', emptyDescription: 'Your project will appear here automatically once it is available.',
    project: 'Your project', domain: 'Domain', openWebsite: 'Open website', support: 'Need help? Contact your team at Naser Solutions.',
    feedback: 'Feedback / change requests', feedbackPlaceholder: 'What would you like us to change?', save: 'Save feedback', saving: 'Saving …',
    logout: 'Sign out', loggingOut: 'Signing out …', portal: 'Client portal', loginDescription: 'Sign in to see the current progress of your project.',
    email: 'Email address', password: 'Password', login: 'Sign in securely', loggingIn: 'Signing in …', restricted: 'Access is reserved for authorized clients.',
    invalidLogin: 'The email address or password is incorrect.', networkError: 'The connection failed. Please try again.',
    invalidFeedback: 'Your input could not be processed.', feedbackTooLong: 'Feedback must not exceed 5,000 characters.',
    sessionExpired: 'Your session has expired. Please sign in again.', saved: 'Your change requests have been saved securely.', saveError: 'Your feedback could not be saved.',
    statusPreparation: 'In preparation', statusActive: 'In progress', statusLive: 'Published', statusPaused: 'Paused',
  },
  fr: {
    selectLanguage: 'Choisir la langue',
    area: 'Votre espace client', welcome: 'Bienvenue', description: 'Retrouvez ici l’avancement et les informations essentielles de votre projet.',
    emptyTitle: 'Aucun projet attribué pour le moment', emptyDescription: 'Votre projet apparaîtra automatiquement ici dès qu’il sera disponible.',
    project: 'Votre projet', domain: 'Domaine', openWebsite: 'Ouvrir le site', support: 'Besoin d’aide ? Contactez votre équipe chez Naser Solutions.',
    feedback: 'Commentaires / demandes de modification', feedbackPlaceholder: 'Quelles modifications souhaitez-vous ?', save: 'Enregistrer les commentaires', saving: 'Enregistrement …',
    logout: 'Se déconnecter', loggingOut: 'Déconnexion …', portal: 'Portail client', loginDescription: 'Connectez-vous pour consulter l’avancement de votre projet.',
    email: 'Adresse e-mail', password: 'Mot de passe', login: 'Se connecter', loggingIn: 'Connexion …', restricted: 'L’accès est réservé aux clients autorisés.',
    invalidLogin: 'L’adresse e-mail ou le mot de passe est incorrect.', networkError: 'La connexion a échoué. Veuillez réessayer.',
    invalidFeedback: 'Votre saisie n’a pas pu être traitée.', feedbackTooLong: 'Les commentaires ne doivent pas dépasser 5 000 caractères.',
    sessionExpired: 'Votre session a expiré. Veuillez vous reconnecter.', saved: 'Vos demandes de modification ont été enregistrées.', saveError: 'Les commentaires n’ont pas pu être enregistrés.',
    statusPreparation: 'En préparation', statusActive: 'En cours', statusLive: 'Publié', statusPaused: 'En pause',
  },
  ar: {
    selectLanguage: 'اختر اللغة',
    area: 'مساحة العملاء', welcome: 'مرحبًا', description: 'هنا تجد آخر المستجدات والمعلومات الأساسية حول مشروعك.',
    emptyTitle: 'لم يتم تعيين مشروع بعد', emptyDescription: 'سيظهر مشروعك هنا تلقائيًا بمجرد إتاحته.',
    project: 'مشروعك', domain: 'النطاق', openWebsite: 'فتح الموقع', support: 'هل تحتاج إلى مساعدة؟ تواصل مع فريقك في Naser Solutions.',
    feedback: 'الملاحظات / طلبات التعديل', feedbackPlaceholder: 'ما التعديلات التي ترغب فيها؟', save: 'حفظ الملاحظات', saving: 'جارٍ الحفظ …',
    logout: 'تسجيل الخروج', loggingOut: 'جارٍ تسجيل الخروج …', portal: 'بوابة العملاء', loginDescription: 'سجّل الدخول للاطلاع على آخر مستجدات مشروعك.',
    email: 'البريد الإلكتروني', password: 'كلمة المرور', login: 'تسجيل الدخول', loggingIn: 'جارٍ تسجيل الدخول …', restricted: 'الدخول مخصص للعملاء المصرّح لهم فقط.',
    invalidLogin: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.', networkError: 'تعذّر الاتصال. يرجى المحاولة مرة أخرى.',
    invalidFeedback: 'تعذّرت معالجة المدخلات.', feedbackTooLong: 'يجب ألا تتجاوز الملاحظات 5000 حرف.',
    sessionExpired: 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.', saved: 'تم حفظ طلبات التعديل بأمان.', saveError: 'تعذّر حفظ الملاحظات.',
    statusPreparation: 'قيد التحضير', statusActive: 'قيد التنفيذ', statusLive: 'منشور', statusPaused: 'متوقف مؤقتًا',
  },
  th: {
    selectLanguage: 'เลือกภาษา',
    area: 'พื้นที่ลูกค้าของคุณ', welcome: 'ยินดีต้อนรับ', description: 'ดูความคืบหน้าล่าสุดและข้อมูลสำคัญเกี่ยวกับโครงการของคุณได้ที่นี่',
    emptyTitle: 'ยังไม่มีโครงการที่ได้รับมอบหมาย', emptyDescription: 'โครงการของคุณจะปรากฏที่นี่โดยอัตโนมัติเมื่อพร้อมใช้งาน',
    project: 'โครงการของคุณ', domain: 'โดเมน', openWebsite: 'เปิดเว็บไซต์', support: 'ต้องการความช่วยเหลือหรือไม่? ติดต่อทีมงานของคุณที่ Naser Solutions',
    feedback: 'ความคิดเห็น / คำขอแก้ไข', feedbackPlaceholder: 'คุณต้องการให้ปรับเปลี่ยนอะไรบ้าง?', save: 'บันทึกความคิดเห็น', saving: 'กำลังบันทึก …',
    logout: 'ออกจากระบบ', loggingOut: 'กำลังออกจากระบบ …', portal: 'พอร์ทัลลูกค้า', loginDescription: 'เข้าสู่ระบบเพื่อดูความคืบหน้าล่าสุดของโครงการของคุณ',
    email: 'ที่อยู่อีเมล', password: 'รหัสผ่าน', login: 'เข้าสู่ระบบ', loggingIn: 'กำลังเข้าสู่ระบบ …', restricted: 'สำหรับลูกค้าที่ได้รับอนุญาตเท่านั้น',
    invalidLogin: 'ที่อยู่อีเมลหรือรหัสผ่านไม่ถูกต้อง', networkError: 'เชื่อมต่อไม่สำเร็จ โปรดลองอีกครั้ง',
    invalidFeedback: 'ไม่สามารถประมวลผลข้อมูลได้', feedbackTooLong: 'ความคิดเห็นต้องไม่เกิน 5,000 ตัวอักษร',
    sessionExpired: 'เซสชันของคุณหมดอายุแล้ว โปรดเข้าสู่ระบบอีกครั้ง', saved: 'บันทึกคำขอแก้ไขของคุณเรียบร้อยแล้ว', saveError: 'ไม่สามารถบันทึกความคิดเห็นได้',
    statusPreparation: 'กำลังเตรียมการ', statusActive: 'กำลังดำเนินการ', statusLive: 'เผยแพร่แล้ว', statusPaused: 'หยุดชั่วคราว',
  },
  hi: {
    selectLanguage: 'भाषा चुनें',
    area: 'आपका ग्राहक क्षेत्र', welcome: 'स्वागत है', description: 'यहाँ अपने प्रोजेक्ट की प्रगति और महत्वपूर्ण जानकारी देखें।',
    emptyTitle: 'अभी कोई प्रोजेक्ट नहीं सौंपा गया है', emptyDescription: 'उपलब्ध होने पर आपका प्रोजेक्ट यहाँ अपने आप दिखाई देगा।',
    project: 'आपका प्रोजेक्ट', domain: 'डोमेन', openWebsite: 'वेबसाइट खोलें', support: 'मदद चाहिए? Naser Solutions की अपनी टीम से संपर्क करें।',
    feedback: 'प्रतिक्रिया / बदलाव के अनुरोध', feedbackPlaceholder: 'आप क्या बदलाव चाहते हैं?', save: 'प्रतिक्रिया सहेजें', saving: 'सहेजा जा रहा है …',
    logout: 'साइन आउट', loggingOut: 'साइन आउट हो रहा है …', portal: 'ग्राहक पोर्टल', loginDescription: 'अपने प्रोजेक्ट की प्रगति देखने के लिए साइन इन करें।',
    email: 'ईमेल पता', password: 'पासवर्ड', login: 'साइन इन करें', loggingIn: 'साइन इन हो रहा है …', restricted: 'केवल अधिकृत ग्राहकों के लिए प्रवेश उपलब्ध है।',
    invalidLogin: 'ईमेल पता या पासवर्ड गलत है।', networkError: 'कनेक्शन विफल रहा। कृपया फिर कोशिश करें।',
    invalidFeedback: 'आपकी जानकारी संसाधित नहीं की जा सकी।', feedbackTooLong: 'प्रतिक्रिया 5,000 अक्षरों से अधिक नहीं हो सकती।',
    sessionExpired: 'आपका सत्र समाप्त हो गया है। कृपया फिर साइन इन करें।', saved: 'आपके बदलाव के अनुरोध सुरक्षित रूप से सहेज दिए गए हैं।', saveError: 'प्रतिक्रिया सहेजी नहीं जा सकी।',
    statusPreparation: 'तैयारी में', statusActive: 'काम जारी है', statusLive: 'प्रकाशित', statusPaused: 'रुका हुआ',
  },
  tr: {
    selectLanguage: 'Dil seçin',
    area: 'Müşteri alanınız', welcome: 'Hoş geldiniz', description: 'Projenizin güncel durumunu ve önemli bilgilerini burada bulabilirsiniz.',
    emptyTitle: 'Henüz proje atanmadı', emptyDescription: 'Projeniz kullanıma açıldığında otomatik olarak burada görünecektir.',
    project: 'Projeniz', domain: 'Alan adı', openWebsite: 'Web sitesini aç', support: 'Yardıma mı ihtiyacınız var? Naser Solutions ekibinizle iletişime geçin.',
    feedback: 'Geri bildirim / değişiklik talepleri', feedbackPlaceholder: 'Hangi değişiklikleri istiyorsunuz?', save: 'Geri bildirimi kaydet', saving: 'Kaydediliyor …',
    logout: 'Çıkış yap', loggingOut: 'Çıkış yapılıyor …', portal: 'Müşteri portalı', loginDescription: 'Projenizin güncel durumunu görmek için giriş yapın.',
    email: 'E-posta adresi', password: 'Şifre', login: 'Giriş yap', loggingIn: 'Giriş yapılıyor …', restricted: 'Erişim yalnızca yetkili müşterilere açıktır.',
    invalidLogin: 'E-posta adresi veya şifre yanlış.', networkError: 'Bağlantı başarısız oldu. Lütfen tekrar deneyin.',
    invalidFeedback: 'Girdiniz işlenemedi.', feedbackTooLong: 'Geri bildirim en fazla 5.000 karakter olabilir.',
    sessionExpired: 'Oturumunuz sona erdi. Lütfen tekrar giriş yapın.', saved: 'Değişiklik talepleriniz güvenle kaydedildi.', saveError: 'Geri bildirim kaydedilemedi.',
    statusPreparation: 'Hazırlık aşamasında', statusActive: 'Devam ediyor', statusLive: 'Yayımlandı', statusPaused: 'Duraklatıldı',
  },
  sq: {
    selectLanguage: 'Zgjidhni gjuhën',
    area: 'Zona juaj e klientit', welcome: 'Mirë se vini', description: 'Këtu gjeni ecurinë aktuale dhe informacionet kryesore të projektit tuaj.',
    emptyTitle: 'Ende nuk është caktuar një projekt', emptyDescription: 'Projekti juaj do të shfaqet automatikisht këtu sapo të jetë i disponueshëm.',
    project: 'Projekti juaj', domain: 'Domeni', openWebsite: 'Hap faqen', support: 'Keni nevojë për ndihmë? Kontaktoni ekipin tuaj te Naser Solutions.',
    feedback: 'Komente / kërkesa për ndryshime', feedbackPlaceholder: 'Çfarë ndryshimesh dëshironi?', save: 'Ruaj komentet', saving: 'Duke ruajtur …',
    logout: 'Dil', loggingOut: 'Duke dalë …', portal: 'Portali i klientit', loginDescription: 'Hyni për të parë ecurinë aktuale të projektit tuaj.',
    email: 'Adresa e emailit', password: 'Fjalëkalimi', login: 'Hyr', loggingIn: 'Duke hyrë …', restricted: 'Hyrja është vetëm për klientët e autorizuar.',
    invalidLogin: 'Adresa e emailit ose fjalëkalimi është i pasaktë.', networkError: 'Lidhja dështoi. Ju lutemi provoni përsëri.',
    invalidFeedback: 'Të dhënat tuaja nuk mund të përpunoheshin.', feedbackTooLong: 'Komentet nuk duhet të kalojnë 5.000 karaktere.',
    sessionExpired: 'Sesioni juaj ka skaduar. Ju lutemi hyni përsëri.', saved: 'Kërkesat tuaja për ndryshime u ruajtën.', saveError: 'Komentet nuk mund të ruheshin.',
    statusPreparation: 'Në përgatitje', statusActive: 'Në punim', statusLive: 'Publikuar', statusPaused: 'Pezulluar',
  },
  ru: {
    selectLanguage: 'Выберите язык',
    area: 'Ваш личный кабинет', welcome: 'Добро пожаловать', description: 'Здесь вы найдёте текущий статус и основную информацию о вашем проекте.',
    emptyTitle: 'Проект пока не назначен', emptyDescription: 'Ваш проект появится здесь автоматически, как только станет доступен.',
    project: 'Ваш проект', domain: 'Домен', openWebsite: 'Открыть сайт', support: 'Нужна помощь? Свяжитесь с вашей командой Naser Solutions.',
    feedback: 'Отзывы / запросы на изменения', feedbackPlaceholder: 'Что вы хотели бы изменить?', save: 'Сохранить отзыв', saving: 'Сохранение …',
    logout: 'Выйти', loggingOut: 'Выход …', portal: 'Клиентский портал', loginDescription: 'Войдите, чтобы посмотреть текущий статус вашего проекта.',
    email: 'Электронная почта', password: 'Пароль', login: 'Войти', loggingIn: 'Вход …', restricted: 'Доступ только для авторизованных клиентов.',
    invalidLogin: 'Неверный адрес электронной почты или пароль.', networkError: 'Не удалось подключиться. Попробуйте ещё раз.',
    invalidFeedback: 'Не удалось обработать введённые данные.', feedbackTooLong: 'Отзыв не должен превышать 5 000 символов.',
    sessionExpired: 'Сессия истекла. Войдите снова.', saved: 'Ваши запросы на изменения сохранены.', saveError: 'Не удалось сохранить отзыв.',
    statusPreparation: 'Подготовка', statusActive: 'В работе', statusLive: 'Опубликован', statusPaused: 'Приостановлен',
  },
  es: {
    selectLanguage: 'Seleccionar idioma',
    area: 'Su área de cliente', welcome: 'Bienvenido', description: 'Aquí encontrará el estado actual y la información principal de su proyecto.',
    emptyTitle: 'Todavía no hay un proyecto asignado', emptyDescription: 'Su proyecto aparecerá aquí automáticamente cuando esté disponible.',
    project: 'Su proyecto', domain: 'Dominio', openWebsite: 'Abrir sitio web', support: '¿Necesita ayuda? Contacte con su equipo de Naser Solutions.',
    feedback: 'Comentarios / solicitudes de cambios', feedbackPlaceholder: '¿Qué cambios desea?', save: 'Guardar comentarios', saving: 'Guardando …',
    logout: 'Cerrar sesión', loggingOut: 'Cerrando sesión …', portal: 'Portal de clientes', loginDescription: 'Inicie sesión para consultar el estado actual de su proyecto.',
    email: 'Correo electrónico', password: 'Contraseña', login: 'Iniciar sesión', loggingIn: 'Iniciando sesión …', restricted: 'El acceso está reservado a clientes autorizados.',
    invalidLogin: 'El correo electrónico o la contraseña son incorrectos.', networkError: 'No se pudo conectar. Inténtelo de nuevo.',
    invalidFeedback: 'No se pudo procesar la información.', feedbackTooLong: 'Los comentarios no pueden superar los 5.000 caracteres.',
    sessionExpired: 'Su sesión ha caducado. Inicie sesión de nuevo.', saved: 'Sus solicitudes de cambios se han guardado.', saveError: 'No se pudieron guardar los comentarios.',
    statusPreparation: 'En preparación', statusActive: 'En curso', statusLive: 'Publicado', statusPaused: 'En pausa',
  },
  it: {
    selectLanguage: 'Seleziona la lingua',
    area: 'La sua area clienti', welcome: 'Benvenuto', description: 'Qui trova lo stato attuale e le informazioni principali del suo progetto.',
    emptyTitle: 'Nessun progetto assegnato al momento', emptyDescription: 'Il suo progetto apparirà automaticamente qui non appena sarà disponibile.',
    project: 'Il suo progetto', domain: 'Dominio', openWebsite: 'Apri il sito', support: 'Serve aiuto? Contatti il suo team di Naser Solutions.',
    feedback: 'Commenti / richieste di modifica', feedbackPlaceholder: 'Quali modifiche desidera?', save: 'Salva i commenti', saving: 'Salvataggio …',
    logout: 'Esci', loggingOut: 'Disconnessione …', portal: 'Portale clienti', loginDescription: 'Acceda per consultare lo stato attuale del suo progetto.',
    email: 'Indirizzo e-mail', password: 'Password', login: 'Accedi', loggingIn: 'Accesso in corso …', restricted: 'L’accesso è riservato ai clienti autorizzati.',
    invalidLogin: 'L’indirizzo e-mail o la password non sono corretti.', networkError: 'Connessione non riuscita. Riprovi.',
    invalidFeedback: 'Non è stato possibile elaborare i dati.', feedbackTooLong: 'I commenti non possono superare i 5.000 caratteri.',
    sessionExpired: 'La sessione è scaduta. Acceda di nuovo.', saved: 'Le sue richieste di modifica sono state salvate.', saveError: 'Non è stato possibile salvare i commenti.',
    statusPreparation: 'In preparazione', statusActive: 'In lavorazione', statusLive: 'Pubblicato', statusPaused: 'In pausa',
  },
  uk: {
    selectLanguage: 'Виберіть мову',
    area: 'Ваш кабінет клієнта', welcome: 'Вітаємо', description: 'Тут ви знайдете поточний стан та основну інформацію про ваш проєкт.',
    emptyTitle: 'Проєкт ще не призначено', emptyDescription: 'Ваш проєкт з’явиться тут автоматично, щойно стане доступним.',
    project: 'Ваш проєкт', domain: 'Домен', openWebsite: 'Відкрити сайт', support: 'Потрібна допомога? Зверніться до вашої команди Naser Solutions.',
    feedback: 'Відгуки / запити на зміни', feedbackPlaceholder: 'Які зміни ви хотіли б внести?', save: 'Зберегти відгук', saving: 'Збереження …',
    logout: 'Вийти', loggingOut: 'Вихід …', portal: 'Портал клієнтів', loginDescription: 'Увійдіть, щоб переглянути поточний стан вашого проєкту.',
    email: 'Електронна пошта', password: 'Пароль', login: 'Увійти', loggingIn: 'Вхід …', restricted: 'Доступ лише для авторизованих клієнтів.',
    invalidLogin: 'Неправильна електронна адреса або пароль.', networkError: 'Не вдалося підключитися. Спробуйте ще раз.',
    invalidFeedback: 'Не вдалося обробити введені дані.', feedbackTooLong: 'Відгук не повинен перевищувати 5 000 символів.',
    sessionExpired: 'Сесія завершилася. Увійдіть знову.', saved: 'Ваші запити на зміни збережено.', saveError: 'Не вдалося зберегти відгук.',
    statusPreparation: 'Підготовка', statusActive: 'У роботі', statusLive: 'Опубліковано', statusPaused: 'Призупинено',
  },
  el: {
    selectLanguage: 'Επιλέξτε γλώσσα',
    area: 'Η περιοχή πελάτη σας', welcome: 'Καλώς ήρθατε', description: 'Εδώ θα βρείτε την τρέχουσα πρόοδο και τις βασικές πληροφορίες του έργου σας.',
    emptyTitle: 'Δεν έχει ανατεθεί ακόμη έργο', emptyDescription: 'Το έργο σας θα εμφανιστεί εδώ αυτόματα μόλις είναι διαθέσιμο.',
    project: 'Το έργο σας', domain: 'Όνομα τομέα', openWebsite: 'Άνοιγμα ιστοσελίδας', support: 'Χρειάζεστε βοήθεια; Επικοινωνήστε με την ομάδα σας στη Naser Solutions.',
    feedback: 'Σχόλια / αιτήματα αλλαγών', feedbackPlaceholder: 'Ποιες αλλαγές θα θέλατε;', save: 'Αποθήκευση σχολίων', saving: 'Αποθήκευση …',
    logout: 'Αποσύνδεση', loggingOut: 'Αποσύνδεση …', portal: 'Πύλη πελατών', loginDescription: 'Συνδεθείτε για να δείτε την τρέχουσα πρόοδο του έργου σας.',
    email: 'Διεύθυνση email', password: 'Κωδικός πρόσβασης', login: 'Σύνδεση', loggingIn: 'Σύνδεση …', restricted: 'Η πρόσβαση επιτρέπεται μόνο σε εξουσιοδοτημένους πελάτες.',
    invalidLogin: 'Το email ή ο κωδικός πρόσβασης είναι λανθασμένα.', networkError: 'Η σύνδεση απέτυχε. Δοκιμάστε ξανά.',
    invalidFeedback: 'Δεν ήταν δυνατή η επεξεργασία των στοιχείων.', feedbackTooLong: 'Τα σχόλια δεν πρέπει να υπερβαίνουν τους 5.000 χαρακτήρες.',
    sessionExpired: 'Η συνεδρία σας έληξε. Συνδεθείτε ξανά.', saved: 'Τα αιτήματα αλλαγών αποθηκεύτηκαν.', saveError: 'Δεν ήταν δυνατή η αποθήκευση των σχολίων.',
    statusPreparation: 'Σε προετοιμασία', statusActive: 'Σε εξέλιξη', statusLive: 'Δημοσιευμένο', statusPaused: 'Σε παύση',
  },
  pt: {
    selectLanguage: 'Selecionar idioma',
    area: 'A sua área de cliente', welcome: 'Bem-vindo', description: 'Aqui encontra o estado atual e as informações principais do seu projeto.',
    emptyTitle: 'Ainda não há um projeto atribuído', emptyDescription: 'O seu projeto aparecerá aqui automaticamente assim que estiver disponível.',
    project: 'O seu projeto', domain: 'Domínio', openWebsite: 'Abrir website', support: 'Precisa de ajuda? Contacte a sua equipa na Naser Solutions.',
    feedback: 'Comentários / pedidos de alteração', feedbackPlaceholder: 'Que alterações pretende?', save: 'Guardar comentários', saving: 'A guardar …',
    logout: 'Terminar sessão', loggingOut: 'A terminar sessão …', portal: 'Portal de clientes', loginDescription: 'Inicie sessão para consultar o estado atual do seu projeto.',
    email: 'Endereço de e-mail', password: 'Palavra-passe', login: 'Iniciar sessão', loggingIn: 'A iniciar sessão …', restricted: 'O acesso é reservado a clientes autorizados.',
    invalidLogin: 'O endereço de e-mail ou a palavra-passe estão incorretos.', networkError: 'A ligação falhou. Tente novamente.',
    invalidFeedback: 'Não foi possível processar os dados.', feedbackTooLong: 'Os comentários não podem exceder 5.000 caracteres.',
    sessionExpired: 'A sua sessão expirou. Inicie sessão novamente.', saved: 'Os seus pedidos de alteração foram guardados.', saveError: 'Não foi possível guardar os comentários.',
    statusPreparation: 'Em preparação', statusActive: 'Em curso', statusLive: 'Publicado', statusPaused: 'Em pausa',
  },
  zh: {
    selectLanguage: '选择语言',
    area: '您的客户专区', welcome: '欢迎', description: '在这里查看项目的最新进展和重要信息。',
    emptyTitle: '尚未分配项目', emptyDescription: '项目开通后会自动显示在这里。',
    project: '您的项目', domain: '域名', openWebsite: '打开网站', support: '需要帮助？请联系您的 Naser Solutions 团队。',
    feedback: '反馈 / 修改请求', feedbackPlaceholder: '您希望进行哪些修改？', save: '保存反馈', saving: '正在保存 …',
    logout: '退出登录', loggingOut: '正在退出 …', portal: '客户门户', loginDescription: '登录以查看项目的最新进展。',
    email: '电子邮箱', password: '密码', login: '登录', loggingIn: '正在登录 …', restricted: '仅限获得授权的客户访问。',
    invalidLogin: '电子邮箱或密码不正确。', networkError: '连接失败，请重试。',
    invalidFeedback: '无法处理输入内容。', feedbackTooLong: '反馈不得超过 5,000 个字符。',
    sessionExpired: '会话已过期，请重新登录。', saved: '您的修改请求已保存。', saveError: '无法保存反馈。',
    statusPreparation: '准备中', statusActive: '进行中', statusLive: '已发布', statusPaused: '已暂停',
  },
}

export const portalStatusKeys = {
  preparation: 'statusPreparation', active: 'statusActive', live: 'statusLive', paused: 'statusPaused',
} as const satisfies Record<string, keyof PortalCopy>
