export interface PortfolioDefault {
 titleKey: string; descriptionKey: string; url: string; tags: string[]; category: string; type?: string; platform?: string; logo?: string; previewImage?: string
}

export const portfolioDefaults: PortfolioDefault[] = [
  {
    titleKey: "projects.cms.title",
    descriptionKey: "projects.cms.description",
    url: "/CMS",
    tags: ["CMS", "Dashboard", "Open Source"],
    category: "web",
    type: "website",
    logo: "/images/logo-invertable.png",
  },
  {
    titleKey: "projects.hazechill.title",
    descriptionKey: "projects.hazechill.description",
    url: "https://www.haze-chill.com/",
    tags: ["Webdesign", "Café", "Kassel"],
    category: "gastro",
    type: "website",
    previewImage: "/projects/haze-chill-website.jpg",
  },
  {
    titleKey: "projects.reel.title",
    descriptionKey: "projects.reel.description",
    url: "https://www.instagram.com/reel/DYug1AZoD9L/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
    tags: ["Instagram", "Reel", "Content Editing", "Social Media"],
    category: "social",
    type: "social",
    platform: "instagram",
    previewImage: "/projects/haze-chill-instagram.png",
  },
  {
    titleKey: "projects.studio.title",
    previewImage: "/projects/studio-glace.jpg",
    descriptionKey: "projects.studio.description",
    url: "https://www.glace14.com/",
    tags: ["Design", "Studio", "Portfolio"],
    category: "design",
    type: "website",
  },
  {
    titleKey: "projects.joesgarage.title",
    logo: "/projects/joes-garage.svg",
    descriptionKey: "projects.joesgarage.description",
    url: "https://www.joes-garage.net",
    tags: ["Rock Bar", "Webdesign", "Events"],
    category: "gastro",
    type: "website",
  },
  {
    titleKey: "projects.crypto.title",
    previewImage: "/projects/crypto-news.jpg",
    descriptionKey: "projects.crypto.description",
    url: "https://v0-crypto-news-website-peach.vercel.app/",
    tags: ["Next.js", "Crypto", "News"],
    category: "web",
    type: "website",
  },
  {
    titleKey: "projects.luxury.title",
    previewImage: "/projects/awd-shop.jpg",
    descriptionKey: "projects.luxury.description",
    url: "https://v0-luxury-street-chic-website.vercel.app/",
    tags: ["Fashion", "E-Commerce", "AWD"],
    category: "ecommerce",
    type: "website",
  },
  {
    titleKey: "projects.donation.title",
    previewImage: "/projects/al-salam.jpg",
    descriptionKey: "projects.donation.description",
    url: "https://v0-donation-website-for-al-salam.vercel.app/",
    tags: ["Charity", "Donation", "Website"],
    category: "nonprofit",
    type: "website",
  },
]
