import type { Language } from "@/components/language-provider"

export const profileCopy: Record<Language, Record<string, string>> = {
  hi: {
    "about.world": "मेरे व्यक्तिगत संपर्क दुनिया भर में, दक्षिण-पूर्व एशिया तक हैं। {ritzi} जैसे परिचितों के साथ मैं पेशेवर सवालों और प्रोजेक्ट पर विचार साझा करता हूँ।",
    "about.community": "मैंने बड़े सर्वरों पर कई मॉडरेटर भूमिकाएँ निभाईं और समुदायों की देखभाल का अनुभव प्राप्त किया। Web3 और क्रिप्टो प्रोजेक्ट में मेरी विशेष रुचि है और इस क्षेत्र में व्यावहारिक अनुभव भी है।",
    "about.cv": "जीवनवृत्त",
    "about.certificates": "प्रमाणपत्र",
    "about.newTab": "नए टैब में खुलता है",
    "services.web.title": "वेब डिज़ाइन और विकास",
    "services.web.description": "स्पष्ट डिज़ाइन, सभी स्क्रीन के अनुकूल लेआउट और ध्यानपूर्वक तकनीकी विकास वाली व्यक्तिगत वेबसाइट — पहली अवधारणा से लेकर दोबारा लॉन्च तक।",
    "services.integrations.title": "इंटीग्रेशन और ऑटोमेशन",
    "services.integrations.description": "फ़ॉर्म, बुकिंग सिस्टम और इंटरफ़ेस जोड़ना। बार-बार होने वाली प्रक्रियाओं को स्वचालित करके हाथ से किए जाने वाले काम को कम करना।",
    "services.design.title": "ब्रांड पहचान और डिज़ाइन",
    "services.design.description": "पहचान बनाने वाला लोगो, रंग और टाइपोग्राफ़ी। आपकी वेबसाइट और डिजिटल चैनलों पर एक समान रूप।",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "सर्च इंजन और AI आधारित खोज के लिए स्पष्ट सामग्री, संरचित डेटा और मज़बूत तकनीकी आधार। बिना सामान्य रैंकिंग की गारंटी दिए।",
    "services.social.title": "सोशल मीडिया और सिनेमैटिक Reels",
    "services.social.description": "सोशल मीडिया सामग्री और सिनेमैटिक Reels: विचार, शूटिंग और संपादन से लेकर आपके चैनल के लिए सही फ़ॉर्मैट तक।",
    "services.care.title": "रखरखाव और आगे का विकास",
    "services.care.description": "अपडेट, सामग्री की देखभाल और लक्षित सुधार आपकी वेबसाइट को आधुनिक बनाए रखते हैं। आपसी सहमति के दायरे में व्यक्तिगत सहायता।"
  },
  th: {
    "about.world": "ฉันมีคนรู้จักทั่วโลกไปจนถึงเอเชียตะวันออกเฉียงใต้ และแลกเปลี่ยนความคิดเห็นด้านงานและโปรเจกต์กับคนรู้จัก เช่น {ritzi}",
    "about.community": "ฉันเคยเป็นผู้ดูแลในเซิร์ฟเวอร์ขนาดใหญ่หลายแห่งและมีประสบการณ์ดูแลชุมชน ฉันสนใจ Web3 และโปรเจกต์คริปโตเป็นพิเศษ และมีประสบการณ์จริงในด้านนี้",
    "about.cv": "ประวัติส่วนตัว",
    "about.certificates": "ใบรับรอง",
    "about.newTab": "เปิดในแท็บใหม่",
    "services.web.title": "ออกแบบและพัฒนาเว็บไซต์",
    "services.web.description": "เว็บไซต์เฉพาะของคุณที่ออกแบบชัดเจน รองรับทุกหน้าจอ และพัฒนาอย่างพิถีพิถัน ตั้งแต่แนวคิดแรกจนถึงการปรับโฉมเว็บไซต์",
    "services.integrations.title": "การเชื่อมต่อระบบและระบบอัตโนมัติ",
    "services.integrations.description": "เชื่อมแบบฟอร์ม ระบบจอง และอินเทอร์เฟซ พร้อมทำขั้นตอนที่เกิดซ้ำให้เป็นอัตโนมัติเพื่อลดงานที่ต้องทำด้วยมือ",
    "services.design.title": "ภาพลักษณ์แบรนด์และการออกแบบ",
    "services.design.description": "โลโก้ สี และตัวอักษรที่ทำให้แบรนด์จดจำได้ พร้อมภาพลักษณ์สอดคล้องกันบนเว็บไซต์และช่องทางดิจิทัลของคุณ",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "เนื้อหาที่ชัดเจน ข้อมูลแบบมีโครงสร้าง และเทคโนโลยีที่เหมาะสมสำหรับเครื่องมือค้นหาและการค้นหาด้วย AI โดยไม่รับประกันอันดับแบบเหมารวม",
    "services.social.title": "โซเชียลมีเดียและ Reels แบบภาพยนตร์",
    "services.social.description": "เนื้อหาโซเชียลมีเดียและ Reels แบบภาพยนตร์ ตั้งแต่ไอเดีย การถ่ายทำและตัดต่อ ไปจนถึงรูปแบบที่เหมาะกับช่องของคุณ",
    "services.care.title": "ดูแลและพัฒนาต่อเนื่อง",
    "services.care.description": "อัปเดต ดูแลเนื้อหา และปรับปรุงอย่างตรงจุดเพื่อให้เว็บไซต์ทันสมัย พร้อมดูแลโดยตรงตามขอบเขตที่ตกลงร่วมกัน"
  },
  uk: {
    "about.world": "Мої особисті контакти охоплюють увесь світ, зокрема Південно-Східну Азію. З такими знайомими, як {ritzi}, я обговорюю професійні питання та проєкти.",
    "about.community": "Я працював модератором на великих серверах і здобув досвід підтримки спільнот. Особливо цікавлюся розвитком Web3 і криптопроєктами; у цій сфері маю практичний досвід.",
    "about.cv": "Резюме",
    "about.certificates": "Свідоцтва",
    "about.newTab": "Відкривається в новій вкладці",
    "services.web.title": "Вебдизайн і веброзробка",
    "services.web.description": "Індивідуальні сайти зі зрозумілим дизайном, адаптивними макетами та ретельною технічною реалізацією — від першої концепції до оновлення сайту.",
    "services.integrations.title": "Інтеграції та автоматизація",
    "services.integrations.description": "Поєднуємо форми, системи бронювання й інтерфейси. Автоматизуємо повторювані процеси, щоб зменшити ручну роботу.",
    "services.design.title": "Образ бренду та дизайн",
    "services.design.description": "Логотип, кольори й типографіка для впізнаваного образу. Узгоджено на твоєму сайті та в цифрових каналах.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Зрозумілий контент, структуровані дані й надійна технічна основа для пошукових систем і пошуку за допомогою ШІ. Без загальних обіцянок щодо позицій у пошуку.",
    "services.social.title": "Соцмережі та кінематографічні Reels",
    "services.social.description": "Контент для соцмереж і кінематографічні Reels: від ідеї, зйомки й монтажу до формату, що підходить твоєму каналу.",
    "services.care.title": "Підтримка та подальший розвиток",
    "services.care.description": "Оновлення, догляд за контентом і цілеспрямовані покращення підтримують актуальність твого сайту. Особистий супровід у погодженому обсязі."
  },
  "de": {
    "about.world": "Meine persönlichen Kontakte reichen über die ganze Welt bis nach Südostasien. Mit Kontakten wie {ritzi} tausche ich mich fachlich zu Fragen und Projekten aus.",
    "about.community": "Ich habe mehrere Moderator-Rollen auf großen Servern übernommen und dabei Erfahrung in der Betreuung von Communities gesammelt. Web3-Entwicklungen und Krypto-Projekte interessieren mich besonders; in diesem Bereich habe ich praktische Erfahrungen gesammelt.",
    "about.cv": "Lebenslauf",
    "about.certificates": "Zeugnisse",
    "about.newTab": "Öffnet in einem neuen Tab",
    "services.web.title": "Webdesign & Webentwicklung",
    "services.web.description": "Individuelle Websites mit klarer Gestaltung, responsiven Layouts und sorgfältiger technischer Umsetzung – vom ersten Konzept bis zum Relaunch.",
    "services.integrations.title": "Integrationen & Automatisierung",
    "services.integrations.description": "Formulare, Buchungssysteme und Schnittstellen verbinden. Wiederkehrende Abläufe automatisieren, damit weniger manuelle Arbeit anfällt.",
    "services.design.title": "Markenauftritt & Gestaltung",
    "services.design.description": "Logo, Farben und Typografie für einen wiedererkennbaren Auftritt. Einheitlich auf deiner Website und in deinen digitalen Kanälen.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Klare Inhalte, strukturierte Daten und saubere Technik für Suchmaschinen und KI-gestützte Suche. Ohne pauschale Ranking-Versprechen.",
    "services.social.title": "Social Media & Cinematic Reels",
    "services.social.description": "Social-Media-Inhalte und filmisch gestaltete Reels: von der Idee über Aufnahme und Schnitt bis zum passenden Format für deinen Kanal.",
    "services.care.title": "Pflege & Weiterentwicklung",
    "services.care.description": "Updates, Inhaltspflege und gezielte Verbesserungen halten deine Website aktuell. Persönliche Betreuung im gemeinsam vereinbarten Umfang."
  },
  "en": {
    "about.world": "My personal connections span the world, reaching Southeast Asia. I exchange ideas on professional questions and projects with contacts such as {ritzi}.",
    "about.community": "I have taken on several moderator roles on large servers, gaining experience supporting communities. I am particularly interested in Web3 developments and crypto projects, and have gained practical experience in this field.",
    "about.cv": "CV",
    "about.certificates": "Certificates",
    "about.newTab": "Opens in a new tab",
    "services.web.title": "Web design & development",
    "services.web.description": "Custom websites with clear design, responsive layouts and careful development, from the first concept to a redesign.",
    "services.integrations.title": "Integrations & automation",
    "services.integrations.description": "Connect forms, booking tools and APIs. Automate recurring tasks to reduce manual work.",
    "services.design.title": "Brand identity & design",
    "services.design.description": "From logos to page layouts: a recognisable presence with a consistent visual language.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Clear content, structured data and sound technical foundations for search engines and AI search, without blanket ranking promises.",
    "services.social.title": "Social media & cinematic reels",
    "services.social.description": "Social content and cinematic reels, from concept and filming to editing and the right format for your channel.",
    "services.care.title": "Care & development",
    "services.care.description": "Update content, improve features and plan the next step, with support scoped to your needs."
  },
  "ru": {
    "about.world": "Мои личные контакты охватывают весь мир, вплоть до Юго-Восточной Азии. С такими контактами, как {ritzi}, я обсуждаю профессиональные вопросы и проекты.",
    "about.community": "Я занимал несколько ролей модератора на крупных серверах и приобрёл опыт поддержки сообществ. Меня особенно интересуют разработки Web3 и криптопроекты, в этой области я получил практический опыт.",
    "about.cv": "Резюме",
    "about.certificates": "Свидетельства",
    "about.newTab": "Открывается в новой вкладке",
    "services.web.title": "Веб-дизайн и разработка",
    "services.web.description": "Понятные страницы, цельный дизайн и удобная мобильная версия.",
    "services.integrations.title": "Интеграции и автоматизация",
    "services.integrations.description": "Соединяем формы, системы бронирования и интерфейсы. Автоматизируем повторяющиеся задачи, сокращая ручную работу.",
    "services.design.title": "Бренд и оформление",
    "services.design.description": "От логотипа до страниц: узнаваемый и последовательный визуальный стиль.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Понятный контент, структурированные данные и техническая основа для поисковых систем и поиска с ИИ, без обещаний позиций.",
    "services.social.title": "Соцсети и кинематографичные Reels",
    "services.social.description": "Контент для соцсетей и кинематографичные Reels: от идеи и съёмки до монтажа и подходящего формата.",
    "services.care.title": "Поддержка и развитие",
    "services.care.description": "Обновление контента и функций в рамках согласованного сопровождения."
  },
  "tr": {
    "about.world": "Kişisel bağlantılarım dünyanın her yerine, Güneydoğu Asya’ya kadar uzanıyor. {ritzi} gibi bağlantılarımla mesleki sorular ve projeler hakkında fikir alışverişi yapıyorum.",
    "about.community": "Büyük sunucularda çeşitli moderatör rolleri üstlenerek topluluklara destek verme deneyimi kazandım. Web3 gelişmeleri ve kripto projeleriyle yakından ilgileniyor, bu alanda pratik deneyim ediniyorum.",
    "about.cv": "Özgeçmiş",
    "about.certificates": "Belgeler",
    "about.newTab": "Yeni sekmede açılır",
    "services.web.title": "Web tasarımı ve geliştirme",
    "services.web.description": "Anlaşılır sayfalar, tutarlı tasarım ve mobil kullanım kolaylığı.",
    "services.integrations.title": "Entegrasyon ve otomasyon",
    "services.integrations.description": "Formları, rezervasyon araçlarını ve arayüzleri bağlamak. Tekrarlanan işleri otomatikleştirerek manuel işi azaltmak.",
    "services.design.title": "Marka kimliği ve tasarım",
    "services.design.description": "Logodan sayfa düzenine kadar tanınabilir bir görsel dil.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Arama motorları ve yapay zekâ araması için anlaşılır içerik, yapılandırılmış veri ve sağlam teknik temel. Sıralama garantisi olmadan.",
    "services.social.title": "Sosyal medya ve sinematik Reels",
    "services.social.description": "Fikirden çekime ve kurguya kadar kanalınıza uygun sosyal içerikler ve sinematik Reels.",
    "services.care.title": "Bakım ve geliştirme",
    "services.care.description": "Anlaşılan kapsamda içerik güncellemeleri ve işlev iyileştirmeleri."
  },
  "ar": {
    "about.world": "تمتد علاقاتي الشخصية حول العالم وصولاً إلى جنوب شرق آسيا. أتبادل الأفكار حول الأسئلة المهنية والمشاريع مع معارف مثل {ritzi}.",
    "about.community": "توليت عدة أدوار للإشراف في خوادم كبيرة واكتسبت خبرة في دعم المجتمعات. أهتم كثيراً بتطورات Web3 ومشاريع العملات الرقمية واكتسبت فيها خبرة عملية.",
    "about.cv": "السيرة الذاتية",
    "about.certificates": "الشهادات",
    "about.newTab": "يفتح في علامة تبويب جديدة",
    "services.web.title": "تصميم وتطوير المواقع",
    "services.web.description": "صفحات واضحة وتصميم متناسق وتجربة مريحة على الهاتف.",
    "services.integrations.title": "التكامل والأتمتة",
    "services.integrations.description": "ربط النماذج وأنظمة الحجز والواجهات. أتمتة المهام المتكررة لتقليل العمل اليدوي.",
    "services.design.title": "الهوية والتصميم",
    "services.design.description": "من الشعار إلى تنسيق الصفحات: لغة بصرية واضحة ومتناسقة.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "محتوى واضح وبيانات منظمة وأساس تقني سليم لمحركات البحث والبحث بالذكاء الاصطناعي، دون وعود بالترتيب.",
    "services.social.title": "التواصل الاجتماعي ومقاطع Reels السينمائية",
    "services.social.description": "محتوى اجتماعي ومقاطع سينمائية، من الفكرة والتصوير إلى المونتاج والصيغة المناسبة لقناتك.",
    "services.care.title": "الصيانة والتطوير",
    "services.care.description": "تحديث المحتوى وتحسين الوظائف وفق نطاق دعم متفق عليه."
  },
  "zh": {
    "about.world": "我的个人联系遍布世界，延伸至东南亚。我与 {ritzi} 等联系人交流专业问题和项目。",
    "about.community": "我曾在大型服务器中担任多个管理员角色，积累了社区管理经验。我对 Web3 发展和加密货币项目很感兴趣，并在这一领域获得了实践经验。",
    "about.cv": "简历",
    "about.certificates": "证书",
    "about.newTab": "在新标签页中打开",
    "services.web.title": "网站设计与开发",
    "services.web.description": "清晰的页面、统一的设计和便捷的移动端体验。",
    "services.integrations.title": "集成与自动化",
    "services.integrations.description": "连接表单、预约系统和接口，自动化重复任务，减少手动工作。",
    "services.design.title": "品牌形象与设计",
    "services.design.description": "从标志到页面布局，建立一致且易于识别的视觉语言。",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "清晰的内容、结构化数据和完善的技术基础，服务于搜索引擎及 AI 搜索，不作排名保证。",
    "services.social.title": "社交媒体与电影感短视频",
    "services.social.description": "社交内容与电影感短视频，从创意、拍摄到剪辑，采用适合渠道的格式。",
    "services.care.title": "维护与改进",
    "services.care.description": "按约定范围更新内容、改进功能并规划下一步。"
  },
  "fr": {
    "about.world": "Mes contacts personnels s’étendent dans le monde entier, jusqu’en Asie du Sud-Est. J’échange sur des questions professionnelles et des projets avec des contacts comme {ritzi}.",
    "about.community": "J’ai occupé plusieurs rôles de modérateur sur de grands serveurs et acquis de l’expérience auprès des communautés. Je m’intéresse particulièrement au Web3 et aux projets crypto, domaines dans lesquels j’ai acquis une expérience pratique.",
    "about.cv": "CV",
    "about.certificates": "Diplômes",
    "about.newTab": "Ouvre un nouvel onglet",
    "services.web.title": "Design & développement web",
    "services.web.description": "Des pages claires, un design cohérent et une utilisation agréable sur mobile.",
    "services.integrations.title": "Intégrations & automatisation",
    "services.integrations.description": "Relier formulaires, outils de réservation et interfaces. Automatiser les tâches récurrentes pour réduire le travail manuel.",
    "services.design.title": "Identité de marque",
    "services.design.description": "Du logo à la mise en page, un langage visuel cohérent et reconnaissable.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Des contenus clairs, des données structurées et une base technique solide pour les moteurs de recherche et la recherche par IA, sans promesse de classement.",
    "services.social.title": "Réseaux sociaux & reels cinématiques",
    "services.social.description": "Contenus sociaux et reels cinématiques, de l’idée au tournage et au montage, adaptés à votre canal.",
    "services.care.title": "Suivi et évolution",
    "services.care.description": "Actualisation des contenus et amélioration des fonctions selon le périmètre convenu."
  },
  "es": {
    "about.world": "Mis contactos personales abarcan todo el mundo, hasta el sudeste asiático. Intercambio ideas sobre cuestiones profesionales y proyectos con contactos como {ritzi}.",
    "about.community": "He asumido varios roles de moderador en grandes servidores y adquirido experiencia apoyando comunidades. Me interesan especialmente los avances de Web3 y los proyectos de criptomonedas, donde he adquirido experiencia práctica.",
    "about.cv": "Currículum",
    "about.certificates": "Certificados",
    "about.newTab": "Abre una nueva pestaña",
    "services.web.title": "Diseño y desarrollo web",
    "services.web.description": "Páginas claras, diseño coherente y una experiencia cómoda en el móvil.",
    "services.integrations.title": "Integraciones y automatización",
    "services.integrations.description": "Conectar formularios, reservas e interfaces. Automatizar tareas recurrentes para reducir el trabajo manual.",
    "services.design.title": "Identidad y diseño",
    "services.design.description": "Del logotipo a las páginas: una imagen reconocible y coherente.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Contenido claro, datos estructurados y una base técnica sólida para buscadores y búsquedas con IA, sin promesas de posicionamiento.",
    "services.social.title": "Redes sociales y reels cinematográficos",
    "services.social.description": "Contenido social y reels cinematográficos, desde la idea y grabación hasta la edición y el formato adecuado.",
    "services.care.title": "Mantenimiento y evolución",
    "services.care.description": "Actualizar contenidos y mejorar funciones según el alcance acordado."
  },
  "it": {
    "about.world": "I miei contatti personali si estendono in tutto il mondo, fino al Sud-est asiatico. Con contatti come {ritzi} mi confronto su questioni professionali e progetti.",
    "about.community": "Ho ricoperto diversi ruoli di moderatore su grandi server, acquisendo esperienza nella gestione delle comunità. Mi interessano molto gli sviluppi Web3 e i progetti crypto, in cui ho maturato esperienza pratica.",
    "about.cv": "Curriculum",
    "about.certificates": "Certificati",
    "about.newTab": "Si apre in una nuova scheda",
    "services.web.title": "Web design e sviluppo",
    "services.web.description": "Pagine chiare, design coerente e un’esperienza comoda anche da mobile.",
    "services.integrations.title": "Integrazioni e automazione",
    "services.integrations.description": "Collegare moduli, prenotazioni e interfacce. Automatizzare le attività ricorrenti per ridurre il lavoro manuale.",
    "services.design.title": "Identità e design",
    "services.design.description": "Dal logo alle pagine, un linguaggio visivo riconoscibile e coerente.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Contenuti chiari, dati strutturati e basi tecniche solide per motori di ricerca e ricerca con IA, senza promesse di posizionamento.",
    "services.social.title": "Social media e reel cinematografici",
    "services.social.description": "Contenuti social e reel cinematografici, dall’idea alle riprese e al montaggio, nel formato adatto al canale.",
    "services.care.title": "Cura ed evoluzione",
    "services.care.description": "Aggiornamenti e miglioramenti delle funzioni secondo gli accordi."
  },
  "pt": {
    "about.world": "Os meus contactos pessoais estendem-se por todo o mundo, até ao Sudeste Asiático. Troco ideias sobre questões profissionais e projetos com contactos como {ritzi}.",
    "about.community": "Assumi vários cargos de moderador em grandes servidores, adquirindo experiência no apoio a comunidades. Interesso-me especialmente pelos desenvolvimentos Web3 e projetos de criptomoedas, nos quais adquiri experiência prática.",
    "about.cv": "Currículo",
    "about.certificates": "Certificados",
    "about.newTab": "Abre num novo separador",
    "services.web.title": "Web design e desenvolvimento",
    "services.web.description": "Páginas claras, design coerente e uma experiência confortável no telemóvel.",
    "services.integrations.title": "Integrações e automação",
    "services.integrations.description": "Ligar formulários, reservas e interfaces. Automatizar tarefas recorrentes para reduzir o trabalho manual.",
    "services.design.title": "Identidade e design",
    "services.design.description": "Do logótipo às páginas, uma linguagem visual coerente e reconhecível.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Conteúdos claros, dados estruturados e bases técnicas sólidas para motores de pesquisa e pesquisa com IA, sem promessas de classificação.",
    "services.social.title": "Redes sociais e reels cinematográficos",
    "services.social.description": "Conteúdos sociais e reels cinematográficos, da ideia à gravação e edição, no formato adequado ao canal.",
    "services.care.title": "Manutenção e evolução",
    "services.care.description": "Atualizações de conteúdo e melhorias de funções conforme o âmbito acordado."
  },
  "el": {
    "about.world": "Οι προσωπικές μου επαφές εκτείνονται σε όλο τον κόσμο, μέχρι τη Νοτιοανατολική Ασία. Με επαφές όπως το {ritzi} ανταλλάσσω απόψεις για επαγγελματικά ζητήματα και έργα.",
    "about.community": "Ανέλαβα αρκετούς ρόλους συντονιστή σε μεγάλους διακομιστές και απέκτησα εμπειρία υποστήριξης κοινοτήτων. Ενδιαφέρομαι ιδιαίτερα για τις εξελίξεις Web3 και τα έργα κρυπτονομισμάτων, όπου έχω αποκτήσει πρακτική εμπειρία.",
    "about.cv": "Βιογραφικό",
    "about.certificates": "Πιστοποιητικά",
    "about.newTab": "Ανοίγει σε νέα καρτέλα",
    "services.web.title": "Σχεδιασμός και ανάπτυξη ιστοσελίδων",
    "services.web.description": "Καθαρές σελίδες, συνεπής εμφάνιση και εύχρηστη προβολή στο κινητό.",
    "services.integrations.title": "Ενσωματώσεις και αυτοματοποίηση",
    "services.integrations.description": "Σύνδεση φορμών, συστημάτων κρατήσεων και διεπαφών. Αυτοματοποίηση επαναλαμβανόμενων εργασιών για λιγότερη χειροκίνητη δουλειά.",
    "services.design.title": "Ταυτότητα και σχεδιασμός",
    "services.design.description": "Από το λογότυπο στις σελίδες, μια αναγνωρίσιμη οπτική γλώσσα.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Σαφές περιεχόμενο, δομημένα δεδομένα και τεχνική βάση για μηχανές αναζήτησης και αναζήτηση με AI, χωρίς υποσχέσεις κατάταξης.",
    "services.social.title": "Social media και κινηματογραφικά Reels",
    "services.social.description": "Περιεχόμενο για social media και κινηματογραφικά Reels, από την ιδέα και τη λήψη έως το μοντάζ.",
    "services.care.title": "Συντήρηση και εξέλιξη",
    "services.care.description": "Ενημέρωση περιεχομένου και βελτίωση λειτουργιών σύμφωνα με τη συμφωνία."
  },
  "sq": {
    "about.world": "Kontaktet e mia personale shtrihen në gjithë botën, deri në Azinë Juglindore. Me kontakte si {ritzi} shkëmbej mendime për pyetje profesionale dhe projekte.",
    "about.community": "Kam marrë disa role moderatori në serverë të mëdhenj dhe kam fituar përvojë në mbështetjen e komuniteteve. Interesohem veçanërisht për zhvillimet Web3 dhe projektet kripto, ku kam fituar përvojë praktike.",
    "about.cv": "CV",
    "about.certificates": "Dëshmi",
    "about.newTab": "Hapet në një skedë të re",
    "services.web.title": "Dizajn dhe zhvillim web",
    "services.web.description": "Faqe të qarta, dizajn i njëtrajtshëm dhe përdorim i rehatshëm në celular.",
    "services.integrations.title": "Integrime dhe automatizim",
    "services.integrations.description": "Lidhje formularësh, sistemesh rezervimi dhe ndërfaqesh. Automatizim i detyrave të përsëritura për më pak punë manuale.",
    "services.design.title": "Identitet dhe dizajn",
    "services.design.description": "Nga logoja te faqet: gjuhë vizuale e dallueshme dhe e qëndrueshme.",
    "services.seo.title": "SEO & GEO",
    "services.seo.description": "Përmbajtje e qartë, të dhëna të strukturuara dhe bazë teknike për motorët e kërkimit dhe kërkimin me AI, pa premtime renditjeje.",
    "services.social.title": "Rrjete sociale dhe Reels kinematografike",
    "services.social.description": "Përmbajtje sociale dhe Reels kinematografike, nga ideja dhe xhirimi te montazhi dhe formati i duhur.",
    "services.care.title": "Mirëmbajtje dhe zhvillim",
    "services.care.description": "Përditësime dhe përmirësime sipas mbështetjes së dakordësuar."
  }
}
