import type { Language } from "@/components/language-provider"

import { japaneseSiteCopy } from './japanese-copy'

export const siteCopy = {
  ja: japaneseSiteCopy,
  hi: {
    "nav.about": "मेरे बारे में",
    "hero.eyebrow": "कासेल की वेब एजेंसी",
    "hero.title1": "आपके अगले कदम के लिए वेब डिज़ाइन और विकास।",
    "hero.description": "मैं व्यवसायों, स्वतंत्र पेशेवरों और क्रिएटर्स के लिए आधुनिक वेबसाइट और डिजिटल ब्रांड पहचान बनाता हूँ। स्पष्ट डिज़ाइन और सोच-समझकर किया गया तकनीकी विकास लोगों को आपकी पेशकश समझने और आपसे संपर्क करने में मदद करता है।",
    "hero.trust": "सीधा संपर्क। स्पष्ट सहमति। सोच-समझकर बनाई गई वेबसाइट।",
    "hero.regions": "कासेल में स्थित, जर्मनी और स्विट्ज़रलैंड में संपर्क।",
    "hero.refBtn": "प्रोजेक्ट देखें",
    "about.title": "Naser Solutions के पीछे का व्यक्ति।",
    "about.description": "मैं <strong>Yasin Adam Aissani</strong> हूँ, कासेल में Naser Solutions का संस्थापक। मैं डिज़ाइन और विकास को जोड़कर ऐसी वेबसाइट बनाता हूँ जो व्यवसाय और उसके लोगों के अनुरूप हों।",
    "about.training": "अभी मैं एप्लिकेशन विकास में IT विशेषज्ञ बनने के लिए व्यावसायिक पुनर्प्रशिक्षण कर रहा हूँ। जो सीखता हूँ, उसे अपने प्रोजेक्ट और वेबसाइट पर व्यावहारिक काम के ज़रिए गहरा करता हूँ।",
    "about.swiss": "स्विट्ज़रलैंड में एक वर्ष के प्रवास के दौरान मेरी इंटर्नशिप एक महत्वपूर्ण अनुभव थी, यहाँ:",
    "about.mentor": "एक अच्छे दोस्त और अनुभवी Senior Full Stack Developer हैं। उन्होंने मुझे शुरू में कोडिंग से परिचित कराया और मित्रतापूर्ण सहयोग से मेरी यात्रा में साथ देते हैं।",
    "about.networkTitle": "व्यक्तिगत संबंध, साथ आगे बढ़ना।",
    "about.network": "मेरे नेटवर्क में स्विट्ज़रलैंड और पूरे जर्मनी की वेब एजेंसियाँ हैं। कासेल में मैं दोस्तों और परिचितों के साथ अपना ज्ञान बाँटता हूँ ताकि उपयुक्त काम हम मिलकर कर सकें।",
    "about.role": "संस्थापक और आपके संपर्क व्यक्ति",
    "about.benefit1": "प्रोजेक्ट पर काम करने वाले व्यक्ति से सीधी बातचीत",
    "about.benefit2": "आपकी ज़रूरत के अनुरूप तकनीक",
    "about.benefit3": "विचार से लॉन्च तक समझने योग्य कदम",
    "about.benefit4": "मिलकर तय किया गया काम का दायरा और बजट",
    "services.title": "अच्छी पहचान की शुरुआत एक स्पष्ट योजना से होती है।",
    "services.description": "हम आपके व्यवसाय की ज़रूरतें समझते हैं और डिज़ाइन, सामग्री और विकास को जोड़कर उपयुक्त डिजिटल समाधान बनाते हैं।",
    "services.web.description": "स्पष्ट डिज़ाइन, सभी स्क्रीन के अनुकूल लेआउट और ध्यानपूर्वक तकनीकी विकास वाली व्यक्तिगत वेबसाइट — पहली अवधारणा से लेकर दोबारा लॉन्च तक।",
    "services.supermarket.title": "खुदरा व्यापार के लिए वेब ऐप",
    "services.supermarket.description": "ऑफ़र, ग्राहक जानकारी और व्यापारिक प्रक्रियाओं के लिए विशेष डिजिटल ऐप। सुविधाएँ और व्यवहार्यता हम पहले मिलकर तय करते हैं।",
    "services.social.description": "सोशल मीडिया सामग्री और सिनेमैटिक Reels: विचार, शूटिंग और संपादन से लेकर आपके चैनल के लिए सही फ़ॉर्मैट तक।",
    "services.design.description": "पहचान बनाने वाला लोगो, रंग और टाइपोग्राफ़ी। आपकी वेबसाइट और डिजिटल चैनलों पर एक समान रूप।",
    "services.seo.description": "सर्च इंजन और AI आधारित खोज के लिए स्पष्ट सामग्री, संरचित डेटा और मज़बूत तकनीकी आधार। बिना सामान्य रैंकिंग की गारंटी दिए।",
    "services.ai.description": "वेबसाइट और सोशल मीडिया के लिए चित्र और वीडियो संपादन, जहाँ AI रचनात्मक प्रक्रिया में उपयोगी सहायता देता है।",
    "projects.badge": "चुनिंदा काम",
    "projects.title": "विचार जो दिखाई देते हैं।",
    "projects.description": "मेरे व्यावहारिक काम से वेबसाइट, डिज़ाइन और सामग्री की झलक। लिंक किए गए प्रोजेक्ट आगे विकसित हो सकते हैं।",
    "vision.label": "मेरा काम करने का तरीका",
    "vision.title": "साथ मिलकर सार्थक विकास।",
    "vision.description": "Naser Solutions व्यावहारिक अनुभव, ईमानदार बातचीत और ज्ञान साझा करने वाले लोगों के साथ बढ़ता है। आपके प्रोजेक्ट के लिए इसका मतलब है वास्तविक कदम और आपकी ज़रूरत के अनुरूप समाधान।",
    "vision.innovation.title": "उपयुक्त तकनीक",
    "vision.innovation.description": "हम आपकी ज़रूरत और भविष्य के रखरखाव के आधार पर उपकरण चुनते हैं।",
    "vision.results.title": "स्पष्ट लक्ष्य",
    "vision.results.description": "हम साथ तय करते हैं कि आपकी वेबसाइट को क्या करना चाहिए और इसे कैसे जाँचेंगे।",
    "vision.creative.title": "अपनी पहचान",
    "vision.creative.description": "डिज़ाइन और सामग्री बताते हैं कि आप कौन हैं और आपकी पेशकश को क्या अलग बनाता है।",
    "vision.partnership.title": "सीधी बातचीत",
    "vision.partnership.description": "आप जानते हैं कि आपके प्रोजेक्ट पर कौन काम कर रहा है, आगे क्या होगा और कौन से निर्णय बाकी हैं।",
    "tools.title": "काम को साकार करने के उपकरण",
    "tools.description": "डिज़ाइन, विकास और चुने हुए AI उपकरण मेरे काम में मदद करते हैं। निर्णायक बात आपके प्रोजेक्ट की ज़रूरत ही रहती है।",
    "contact.title": "आपकी योजना क्या है?",
    "contact.description": "अपना विचार, मौजूदा वेबसाइट या व्यवसाय का अगला कदम साझा करें। हम साथ मिलकर दायरा, संभावनाएँ और उपयुक्त तरीका तय करेंगे।",
    "contact.city": "कासेल, जर्मनी",
    "contact.form.title": "आपके प्रोजेक्ट पर बात करें।",
    "contact.form.intro": "शुरुआत के लिए कुछ वाक्य पर्याप्त हैं। मैं व्यक्तिगत रूप से जवाब दूँगा।",
    "contact.form.privacy": "आपकी जानकारी का उपयोग अनुरोध पर काम करने के लिए होता है। विवरण:",
    "contact.form.messagePlaceholder": "आपको क्या चाहिए? क्या कोई वेबसाइट, समय-सीमा या बजट पहले से है?",
    "contact.form.success": "आपके संदेश के लिए धन्यवाद। मैं व्यक्तिगत रूप से आपसे संपर्क करूँगा।",
    "contact.form.error": "संदेश भेजे जाने की पुष्टि नहीं हो सकी। कृपया सीधे ईमेल से संपर्क करें।",
    "about.family": "2025 के अंत में मैं एक बेटे का पिता बना। उसी के नाम से Naser Solutions का नाम आया। दिसंबर 2025 से मैं कासेल में रहता हूँ; इससे पहले बवेरिया में अपनी माँ और भाई-बहनों के साथ रहता था।",
    "about.backgroundTitle": "मेरी यात्रा के बारे में और जानें",
    "about.school": "मैंने जर्मनी की Mittlere Reife माध्यमिक योग्यता अपनी कक्षा में सबसे अच्छे परिणाम के साथ पूरी की। स्कूल में मैं मुख्य छात्र प्रतिनिधि भी रहा।",
    "about.bundeswehr": "मैंने कुछ समय जर्मन सेना में सेवा की और बुनियादी प्रशिक्षण पूरा किया। मेरी रैंक Gefreiter है; मुख्य भूमिका IT सैनिक और दूसरी भूमिका मेडिक की थी।"
  },
  th: {
    "nav.about": "เกี่ยวกับฉัน",
    "hero.eyebrow": "เว็บเอเจนซีจากคัสเซิล",
    "hero.title1": "ออกแบบและพัฒนาเว็บไซต์สำหรับก้าวต่อไปของคุณ",
    "hero.description": "ฉันสร้างเว็บไซต์สมัยใหม่และภาพลักษณ์แบรนด์ดิจิทัลสำหรับธุรกิจ ผู้ประกอบอาชีพอิสระ และครีเอเตอร์ ด้วยการออกแบบที่ชัดเจนและเทคโนโลยีที่วางแผนอย่างรอบคอบ เพื่อให้ผู้คนเข้าใจสิ่งที่คุณนำเสนอและติดต่อคุณได้ง่ายขึ้น",
    "hero.trust": "ติดต่อโดยตรง ข้อตกลงชัดเจน เว็บไซต์ที่คิดมาอย่างรอบคอบ",
    "hero.regions": "อยู่ที่คัสเซิล พร้อมเครือข่ายในเยอรมนีและสวิตเซอร์แลนด์",
    "hero.refBtn": "ดูโปรเจกต์",
    "about.title": "คนเบื้องหลัง Naser Solutions",
    "about.description": "ฉันคือ <strong>Yasin Adam Aissani</strong> ผู้ก่อตั้ง Naser Solutions ในคัสเซิล ฉันผสานการออกแบบและการพัฒนาให้เป็นเว็บไซต์ที่เหมาะกับธุรกิจและผู้คนในธุรกิจนั้น",
    "about.training": "ตอนนี้ฉันกำลังเรียนเปลี่ยนสายอาชีพเป็นผู้เชี่ยวชาญไอทีด้านพัฒนาแอปพลิเคชัน โดยนำสิ่งที่เรียนมาต่อยอดในโปรเจกต์ของตัวเองและการทำเว็บไซต์จริง",
    "about.swiss": "ประสบการณ์สำคัญคือการฝึกงานระหว่างที่ฉันใช้ชีวิตหนึ่งปีในสวิตเซอร์แลนด์กับ",
    "about.mentor": "เป็นเพื่อนที่ดีและนักพัฒนา Senior Full Stack ที่มีประสบการณ์ เขาเป็นคนเริ่มพาฉันเข้าสู่การเขียนโค้ด และคอยสนับสนุนเส้นทางของฉันอย่างเป็นมิตร",
    "about.networkTitle": "เชื่อมโยงกันด้วยมิตรภาพ ก้าวต่อไปด้วยกัน",
    "about.network": "เครือข่ายของฉันมีเว็บเอเจนซีในสวิตเซอร์แลนด์และทั่วเยอรมนี ในคัสเซิลฉันแบ่งปันความรู้กับเพื่อนและคนรู้จัก เพื่อร่วมกันทำงานที่เหมาะสม",
    "about.role": "ผู้ก่อตั้งและผู้ติดต่อของคุณ",
    "about.benefit1": "พูดคุยโดยตรงกับคนที่ทำโปรเจกต์",
    "about.benefit2": "เทคโนโลยีที่เหมาะกับสิ่งที่คุณต้องการ",
    "about.benefit3": "ขั้นตอนเข้าใจง่ายตั้งแต่ไอเดียจนเปิดตัว",
    "about.benefit4": "ขอบเขตงานและงบประมาณที่ตกลงร่วมกัน",
    "services.title": "ภาพลักษณ์ที่ดีเริ่มจากแผนที่ชัดเจน",
    "services.description": "เราทำความเข้าใจความต้องการของธุรกิจคุณ แล้วเชื่อมการออกแบบ เนื้อหา และการพัฒนาเข้าด้วยกันเป็นโซลูชันดิจิทัลที่เหมาะสม",
    "services.web.description": "เว็บไซต์เฉพาะของคุณที่ออกแบบชัดเจน รองรับทุกหน้าจอ และพัฒนาอย่างพิถีพิถัน ตั้งแต่แนวคิดแรกจนถึงการปรับโฉมเว็บไซต์",
    "services.supermarket.title": "เว็บแอปสำหรับธุรกิจค้าปลีก",
    "services.supermarket.description": "แอปดิจิทัลเฉพาะสำหรับข้อเสนอ ข้อมูลลูกค้า และกระบวนการค้าปลีก โดยตกลงฟังก์ชันและความเป็นไปได้ร่วมกันล่วงหน้า",
    "services.social.description": "เนื้อหาโซเชียลมีเดียและ Reels แบบภาพยนตร์ ตั้งแต่ไอเดีย การถ่ายทำและตัดต่อ ไปจนถึงรูปแบบที่เหมาะกับช่องของคุณ",
    "services.design.description": "โลโก้ สี และตัวอักษรที่ทำให้แบรนด์จดจำได้ พร้อมภาพลักษณ์สอดคล้องกันบนเว็บไซต์และช่องทางดิจิทัลของคุณ",
    "services.seo.description": "เนื้อหาที่ชัดเจน ข้อมูลแบบมีโครงสร้าง และเทคโนโลยีที่เหมาะสมสำหรับเครื่องมือค้นหาและการค้นหาด้วย AI โดยไม่รับประกันอันดับแบบเหมารวม",
    "services.ai.description": "ปรับแต่งภาพและวิดีโอสำหรับเว็บไซต์และโซเชียลมีเดีย โดยใช้ AI ในจุดที่ช่วยสนับสนุนกระบวนการสร้างสรรค์ได้อย่างเหมาะสม",
    "projects.badge": "ผลงานที่คัดเลือก",
    "projects.title": "ไอเดียที่มองเห็นได้จริง",
    "projects.description": "ตัวอย่างเว็บไซต์ การออกแบบ และเนื้อหาจากงานจริงของฉัน โปรเจกต์ที่เชื่อมโยงไว้อาจมีการพัฒนาต่อ",
    "vision.label": "แนวทางการทำงานของฉัน",
    "vision.title": "เติบโตไปด้วยกันอย่างมีความหมาย",
    "vision.description": "Naser Solutions เติบโตจากประสบการณ์จริง การพูดคุยอย่างตรงไปตรงมา และผู้คนที่แบ่งปันความรู้ สำหรับโปรเจกต์ของคุณ นั่นคือขั้นตอนที่ทำได้จริงและโซลูชันที่ตรงกับความต้องการ",
    "vision.innovation.title": "เทคโนโลยีที่เหมาะสม",
    "vision.innovation.description": "เราเลือกเครื่องมือตามความต้องการของคุณและการดูแลในอนาคต",
    "vision.results.title": "เป้าหมายชัดเจน",
    "vision.results.description": "เรากำหนดร่วมกันว่าเว็บไซต์ของคุณควรทำอะไรได้ และจะตรวจสอบอย่างไร",
    "vision.creative.title": "เอกลักษณ์ของคุณ",
    "vision.creative.description": "การออกแบบและเนื้อหาสื่อว่าคุณคือใครและข้อเสนอของคุณโดดเด่นอย่างไร",
    "vision.partnership.title": "สื่อสารโดยตรง",
    "vision.partnership.description": "คุณรู้ว่าใครทำโปรเจกต์ให้คุณ ขั้นตอนต่อไปคืออะไร และยังมีเรื่องใดที่ต้องตัดสินใจ",
    "tools.title": "เครื่องมือสำหรับลงมือทำ",
    "tools.description": "การออกแบบ การพัฒนา และเครื่องมือ AI ที่คัดเลือกช่วยในการทำงานของฉัน สิ่งสำคัญที่สุดยังเป็นความต้องการของโปรเจกต์คุณ",
    "contact.title": "คุณมีแผนอะไร?",
    "contact.description": "เล่าไอเดีย เว็บไซต์ที่มีอยู่ หรือก้าวต่อไปของธุรกิจคุณให้ฉันฟัง เราจะกำหนดขอบเขต ความเป็นไปได้ และแนวทางที่เหมาะสมร่วมกัน",
    "contact.city": "คัสเซิล เยอรมนี",
    "contact.form.title": "มาคุยเรื่องโปรเจกต์ของคุณกัน",
    "contact.form.intro": "เริ่มด้วยข้อความสั้น ๆ สักสองสามประโยคก็พอ ฉันจะตอบกลับเอง",
    "contact.form.privacy": "ฉันใช้ข้อมูลของคุณเพื่อดำเนินการตามคำถาม รายละเอียด:",
    "contact.form.messagePlaceholder": "คุณต้องการอะไร? มีเว็บไซต์ กำหนดเวลา หรืองบประมาณแล้วหรือยัง?",
    "contact.form.success": "ขอบคุณสำหรับข้อความ ฉันจะติดต่อกลับด้วยตัวเอง",
    "contact.form.error": "ยังยืนยันการส่งข้อความไม่ได้ กรุณาติดต่อฉันโดยตรงทางอีเมล",
    "about.family": "ตั้งแต่ปลายปี 2025 ฉันเป็นพ่อของลูกชาย ชื่อของเขาคือที่มาของ Naser Solutions ฉันย้ายมาอยู่คัสเซิลในเดือนธันวาคม 2025 ก่อนหน้านั้นอยู่บาวาเรียกับแม่และพี่น้อง",
    "about.backgroundTitle": "เรื่องราวเส้นทางของฉัน",
    "about.school": "ฉันจบการศึกษาระดับ Mittlere Reife ของเยอรมนีด้วยผลการเรียนดีที่สุดในชั้น และเคยเป็นหัวหน้าตัวแทนนักเรียน",
    "about.bundeswehr": "ฉันเคยรับราชการช่วงสั้น ๆ ในกองทัพเยอรมันและผ่านการฝึกพื้นฐาน ยศของฉันคือ Gefreiter หน้าที่หลักเป็นทหารไอที และหน้าที่รองเป็นทหารแพทย์"
  },
  uk: {
    "nav.about": "Про мене",
    "hero.eyebrow": "Вебагенція з Касселя",
    "hero.title1": "Вебдизайн і розробка для твого наступного кроку.",
    "hero.description": "Я створюю сучасні сайти й цифровий образ бренду для компаній, самозайнятих фахівців і авторів контенту. Зрозумілий дизайн і продумана технічна реалізація допомагають представити твою пропозицію та спрощують звернення клієнтів.",
    "hero.trust": "Особистий контакт. Чіткі домовленості. Продумані сайти.",
    "hero.regions": "Живу в Касселі, підтримую контакти в Німеччині та Швейцарії.",
    "hero.refBtn": "Переглянути проєкти",
    "about.title": "Людина за Naser Solutions.",
    "about.description": "Я <strong>Yasin Adam Aissani</strong>, засновник Naser Solutions у Касселі. Я поєдную дизайн і розробку в сайтах, що відповідають компанії та її людям.",
    "about.training": "Зараз я проходжу професійну перепідготовку за спеціальністю розробки програмного забезпечення. Поглиблюю здобуті знання у власних проєктах і практичній роботі над сайтами.",
    "about.swiss": "Важливим етапом стало моє стажування під час річного перебування у Швейцарії в",
    "about.mentor": "— мій добрий друг і досвідчений Senior Full Stack Developer. Він свого часу зацікавив мене програмуванням і підтримує мене на цьому шляху.",
    "about.networkTitle": "Особисті зв’язки, спільний рух уперед.",
    "about.network": "Моя мережа контактів охоплює вебагенції у Швейцарії та по всій Німеччині. У Касселі я ділюся знаннями з друзями й знайомими, щоб разом працювати над відповідними замовленнями.",
    "about.role": "Засновник і твоя контактна особа",
    "about.benefit1": "Безпосереднє спілкування з людиною, яка працює над проєктом",
    "about.benefit2": "Технології, що відповідають твоїм потребам",
    "about.benefit3": "Зрозумілі кроки від ідеї до запуску",
    "about.benefit4": "Спільно погоджені обсяг робіт і бюджет",
    "services.title": "Гарна присутність починається з чіткого плану.",
    "services.description": "Ми з’ясовуємо потреби твоєї компанії та поєднуємо дизайн, контент і розробку у відповідне цифрове рішення.",
    "services.web.description": "Індивідуальні сайти зі зрозумілим дизайном, адаптивними макетами та ретельною технічною реалізацією — від першої концепції до оновлення сайту.",
    "services.supermarket.title": "Вебзастосунки для торгівлі",
    "services.supermarket.description": "Індивідуальні цифрові застосунки для пропозицій, інформації для клієнтів і торговельних процесів. Функції та можливість реалізації узгоджуємо заздалегідь.",
    "services.social.description": "Контент для соцмереж і кінематографічні Reels: від ідеї, зйомки й монтажу до формату, що підходить твоєму каналу.",
    "services.design.description": "Логотип, кольори й типографіка для впізнаваного образу. Узгоджено на твоєму сайті та в цифрових каналах.",
    "services.seo.description": "Зрозумілий контент, структуровані дані й надійна технічна основа для пошукових систем і пошуку за допомогою ШІ. Без загальних обіцянок щодо позицій у пошуку.",
    "services.ai.description": "Обробка зображень і відео для сайту та соцмереж із використанням ШІ там, де він доцільно підтримує творчий процес.",
    "projects.badge": "Вибрані роботи",
    "projects.title": "Ідеї, що стають видимими.",
    "projects.description": "Сайти, дизайн і контент із моєї практичної роботи. Проєкти за посиланнями можуть розвиватися далі.",
    "vision.label": "Мій підхід до роботи",
    "vision.title": "Разом розвиватися з користю.",
    "vision.description": "Naser Solutions зростає завдяки практичному досвіду, чесному спілкуванню й людям, які діляться знаннями. Для твого проєкту це означає реалістичні кроки та рішення, що відповідають твоїм потребам.",
    "vision.innovation.title": "Відповідні технології",
    "vision.innovation.description": "Ми обираємо інструменти відповідно до твоїх вимог і майбутньої підтримки.",
    "vision.results.title": "Чіткі цілі",
    "vision.results.description": "Разом визначаємо, що має робити твій сайт і як ми це перевірятимемо.",
    "vision.creative.title": "Власний характер",
    "vision.creative.description": "Дизайн і контент показують, хто ти та чим вирізняється твоя пропозиція.",
    "vision.partnership.title": "Безпосереднє спілкування",
    "vision.partnership.description": "Ти знаєш, хто працює над твоїм проєктом, що буде далі та які рішення ще потрібно ухвалити.",
    "tools.title": "Інструменти для реалізації",
    "tools.description": "Дизайн, розробка й вибрані інструменти ШІ підтримують мою роботу. Вирішальними залишаються потреби твого проєкту.",
    "contact.title": "Що ти плануєш?",
    "contact.description": "Розкажи про свою ідею, наявний сайт або наступний крок для компанії. Разом визначимо обсяг, можливості та відповідний підхід.",
    "contact.city": "Кассель, Німеччина",
    "contact.form.title": "Обговорімо твій проєкт.",
    "contact.form.intro": "Для початку достатньо кількох речень. Я відповім особисто.",
    "contact.form.privacy": "Я використовую твої дані для опрацювання запиту. Докладніше:",
    "contact.form.messagePlaceholder": "Що тобі потрібно? Чи є вже сайт, терміни або бюджет?",
    "contact.form.success": "Дякую за повідомлення. Я зв’яжуся з тобою особисто.",
    "contact.form.error": "Не вдалося підтвердити надсилання повідомлення. Будь ласка, напиши мені безпосередньо на електронну пошту.",
    "about.family": "Наприкінці 2025 року я став батьком сина. Від його імені походить назва Naser Solutions. З грудня 2025 року я живу в Касселі; раніше жив у Баварії з мамою, братами та сестрами.",
    "about.backgroundTitle": "Більше про мій шлях",
    "about.school": "Я здобув німецький атестат Mittlere Reife з найкращим результатом у класі. У школі також був головним представником учнів.",
    "about.bundeswehr": "Я недовго служив у Бундесвері та завершив базову підготовку. Моє звання — Gefreiter; основна спеціальність — ІТ-солдат, додаткова — медик."
  },
  "de": {
    "nav.about": "Über mich",
    "hero.eyebrow": "Webagentur aus Kassel",
    "hero.title1": "Webdesign & Entwicklung für deinen nächsten Schritt.",
    "hero.description": "Ich entwickle moderne Websites und digitale Markenauftritte für Unternehmen, Selbstständige und Creator. Klar im Design, durchdacht in der Technik und darauf ausgerichtet, dein Angebot verständlich zu machen und Anfragen zu erleichtern.",
    "hero.trust": "Persönlicher Kontakt. Klare Absprachen. Durchdachte Websites.",
    "hero.regions": "In Kassel zu Hause, mit Kontakten in Deutschland und der Schweiz.",
    "hero.refBtn": "Projekte entdecken",
    "about.title": "Der Mensch hinter Naser Solutions.",
    "about.description": "Ich bin <strong>Yasin Adam Aissani</strong>, Gründer von Naser Solutions in Kassel. Ich verbinde Gestaltung und Entwicklung zu Webauftritten, die zum Unternehmen und seinen Menschen passen.",
    "about.training": "Aktuell mache ich eine Umschulung zum Fachinformatiker für Anwendungsentwicklung. Was ich lerne, vertiefe ich in eigenen Projekten und in der praktischen Arbeit an Websites.",
    "about.swiss": "Ein wichtiger Baustein war mein Praktikum während meines einjährigen Aufenthalts in der Schweiz bei",
    "about.mentor": "ist ein guter Freund und langjähriger Senior-Full-Stack-Developer. Er hat mich ursprünglich zum Coden gebracht und begleitet meinen Weg mit freundschaftlicher Unterstützung.",
    "about.networkTitle": "Persönlich verbunden, gemeinsam weiter.",
    "about.network": "Mein Netzwerk umfasst Webagenturen in der Schweiz und ganz Deutschland. In Kassel gebe ich mein Wissen an Freunde und Bekannte weiter, um geeignete Aufträge gemeinsam bearbeiten zu können.",
    "about.role": "Gründer & dein Ansprechpartner",
    "about.benefit1": "Direkter Austausch mit dem Menschen hinter dem Projekt",
    "about.benefit2": "Technik, die zu deinem Vorhaben passt",
    "about.benefit3": "Verständliche Schritte von der Idee bis zum Launch",
    "about.benefit4": "Ein gemeinsam abgestimmter Umfang und Budgetrahmen",
    "services.title": "Ein guter Auftritt beginnt mit einem klaren Plan.",
    "services.description": "Wir klären, was dein Unternehmen braucht, und verbinden Gestaltung, Inhalte und Entwicklung zu einer passenden digitalen Lösung.",
    "services.web.description": "Von der Struktur bis zur Umsetzung: moderne, responsive Websites mit klaren Inhalten, kurzen Wegen und einer wartbaren technischen Grundlage.",
    "services.supermarket.title": "Web-Apps für den Handel",
    "services.supermarket.description": "Individuelle digitale Anwendungen für Angebote, Kundeninformationen und Abläufe im Handel. Funktionen und Machbarkeit stimmen wir vorab gemeinsam ab.",
    "services.social.description": "Inhalte und visuelle Konzepte für deine Social-Media-Kanäle. Kampagnen planen wir passend zu Zielgruppe, Budget und vereinbarten Zielen.",
    "services.design.description": "Logos, Farben und Gestaltungselemente, die zusammenpassen. Für einen wiedererkennbaren Auftritt auf deiner Website und in deinen Medien.",
    "services.seo.description": "Saubere Seitenstruktur, hilfreiche Texte und optimierte Ladezeiten als Grundlage dafür, dass Menschen und Suchmaschinen dein Angebot verstehen.",
    "services.ai.description": "Bild- und Videobearbeitung für Website und Social Media, mit KI dort, wo sie den kreativen Prozess sinnvoll unterstützt.",
    "projects.badge": "Ausgewählte Arbeiten",
    "projects.title": "Ideen, die sichtbar werden.",
    "projects.description": "Einblicke in Websites, Gestaltung und Content aus meiner praktischen Arbeit. Die verlinkten Projektstände können sich weiterentwickeln.",
    "vision.label": "Meine Arbeitsweise",
    "vision.title": "Gemeinsam sinnvoll wachsen.",
    "vision.description": "Naser Solutions wächst mit praktischer Erfahrung, ehrlichem Austausch und Menschen, die ihr Wissen teilen. Für dein Projekt bedeutet das: realistische Schritte und Lösungen, die zu deinem Bedarf passen.",
    "vision.innovation.title": "Passende Technik",
    "vision.innovation.description": "Wir wählen Werkzeuge nach deinen Anforderungen und der späteren Pflege aus.",
    "vision.results.title": "Klare Ziele",
    "vision.results.description": "Wir legen gemeinsam fest, was deine Website leisten soll und wie wir das überprüfen.",
    "vision.creative.title": "Eigener Charakter",
    "vision.creative.description": "Gestaltung und Inhalte machen deutlich, wer du bist und was dein Angebot auszeichnet.",
    "vision.partnership.title": "Direkter Austausch",
    "vision.partnership.description": "Du weißt, wer an deinem Projekt arbeitet, was als Nächstes ansteht und welche Entscheidungen offen sind.",
    "tools.title": "Werkzeuge für die Umsetzung",
    "tools.description": "Design, Entwicklung und ausgewählte KI-Werkzeuge unterstützen meine Arbeit. Entscheidend bleibt, was dein Projekt braucht.",
    "contact.title": "Was hast du vor?",
    "contact.description": "Erzähl mir von deiner Idee, einer bestehenden Website oder dem nächsten Schritt für dein Unternehmen. Gemeinsam klären wir Umfang, Möglichkeiten und ein passendes Vorgehen.",
    "contact.city": "Kassel, Deutschland",
    "contact.form.title": "Lass uns über dein Projekt sprechen.",
    "contact.form.intro": "Ein paar Sätze reichen für den Anfang. Ich melde mich persönlich.",
    "contact.form.privacy": "Deine Angaben nutze ich zur Bearbeitung deiner Anfrage. Details:",
    "contact.form.messagePlaceholder": "Was brauchst du? Gibt es schon eine Website, einen Zeitrahmen oder ein Budget?",
    "contact.form.success": "Danke für deine Nachricht. Ich melde mich persönlich bei dir.",
    "contact.form.error": "Die Nachricht konnte nicht bestätigt werden. Bitte kontaktiere mich direkt per E-Mail.",
    "about.family": "Seit Ende 2025 bin ich Vater eines Sohnes. Von seinem Namen leitet sich Naser Solutions ab. Seit Dezember 2025 lebe ich in Kassel; davor wohnte ich in Bayern bei meiner Mutter und meinen Geschwistern.",
    "about.backgroundTitle": "Mehr über meinen Weg",
    "about.school": "Meine Mittlere Reife habe ich als Klassenbester abgeschlossen. In der Schule habe ich mich außerdem als erster Schülersprecher engagiert.",
    "about.bundeswehr": "Ich war kurz bei der Bundeswehr und habe dort meine Grundausbildung abgeschlossen. Mein Dienstgrad ist Gefreiter; meine Verwendung war IT-Soldat, sekundär Medic.",
  },
  "en": {
    "nav.about": "About me",
    "hero.eyebrow": "Web agency in Kassel",
    "hero.title1": "Web design & development for your next step.",
    "hero.description": "I build modern websites and digital brand identities for businesses, independent professionals and creators. Clear design and thoughtful development help people understand your offer and get in touch.",
    "hero.trust": "Personal contact. Clear agreements. Thoughtful websites.",
    "hero.regions": "Based in Kassel, connected across Germany and Switzerland.",
    "hero.refBtn": "Explore projects",
    "about.title": "The person behind Naser Solutions.",
    "about.description": "I'm <strong>Yasin Adam Aissani</strong>, founder of Naser Solutions in Kassel. I bring design and development together to create websites that fit a business and its people.",
    "about.training": "I'm currently retraining as an IT specialist in application development. I deepen what I learn through my own projects and hands-on website work.",
    "about.swiss": "An important step was my internship during a year living in Switzerland at",
    "about.mentor": "is a close friend and experienced senior full-stack developer. He first got me into coding and continues to support me as a friend.",
    "about.networkTitle": "Personal connections. Shared progress.",
    "about.network": "My network includes web agencies across Switzerland and Germany. In Kassel, I share my knowledge with friends and acquaintances so we can collaborate on suitable projects.",
    "about.role": "Founder & your contact",
    "about.benefit1": "Direct contact with the person behind your project",
    "about.benefit2": "Technology suited to your needs",
    "about.benefit3": "Clear steps from idea to launch",
    "about.benefit4": "An agreed scope and budget",
    "services.title": "A good website starts with a clear plan.",
    "services.description": "We establish what your business needs, then combine design, content and development into a fitting digital solution.",
    "services.web.description": "From structure to delivery: modern, responsive websites with clear content, straightforward navigation and a maintainable technical foundation.",
    "services.supermarket.title": "Web apps for retail",
    "services.supermarket.description": "Custom digital tools for offers, customer information and retail workflows. We agree on features and feasibility before development.",
    "services.social.description": "Content and visual concepts for your social channels. Campaigns are planned around your audience, budget and agreed goals.",
    "services.design.description": "Logos, colours and design elements that work together. A recognisable identity for your website and other media.",
    "services.seo.description": "Clear page structure, useful copy and improved load times help people and search engines understand your offer.",
    "services.ai.description": "Image and video editing for websites and social media, using AI where it meaningfully supports creative work.",
    "projects.badge": "Selected work",
    "projects.title": "Ideas taking shape.",
    "projects.description": "Websites, design and content from my practical work. The linked projects may continue to evolve.",
    "vision.label": "How I work",
    "vision.title": "Growing together, step by step.",
    "vision.description": "Naser Solutions grows through hands-on experience, honest conversations and shared knowledge. For your project, that means realistic steps and solutions that fit your needs.",
    "vision.innovation.title": "Suitable technology",
    "vision.innovation.description": "We choose tools around your requirements and future maintenance.",
    "vision.results.title": "Clear goals",
    "vision.results.description": "Together we define what your website should do and how to check the result.",
    "vision.creative.title": "Your character",
    "vision.creative.description": "Design and content show who you are and what makes your offer distinctive.",
    "vision.partnership.title": "Direct communication",
    "vision.partnership.description": "You know who is working on your project, what comes next and which decisions remain open.",
    "tools.title": "Tools for the work",
    "tools.description": "Design, development and selected AI tools support my work. Your project's needs guide the choice.",
    "contact.title": "What are you planning?",
    "contact.description": "Tell me about your idea, an existing website or the next step for your business. Together we can work out the scope, possibilities and approach.",
    "contact.city": "Kassel, Germany",
    "contact.form.title": "Let's talk about your project.",
    "contact.form.intro": "A few sentences are enough to start. I'll reply personally.",
    "contact.form.privacy": "I use your details to respond to your enquiry. Details:",
    "contact.form.messagePlaceholder": "What do you need? Do you have a website, timeframe or budget?",
    "contact.form.success": "Thanks for your message. I'll get back to you personally.",
    "contact.form.error": "Your message could not be confirmed. Please contact me directly by email.",
    "about.family": "I became a father to a son in late 2025. His name inspired Naser Solutions. I have lived in Kassel since December 2025; before that, I lived in Bavaria with my mother and siblings.",
    "about.backgroundTitle": "More about my journey",
    "about.school": "I completed my German intermediate secondary school certificate at the top of my class and also served as the lead student representative.",
    "about.bundeswehr": "I briefly served in the German Bundeswehr and completed basic training. My rank is Gefreiter; my assignment was IT soldier, with a secondary medic role.",
  },
  "fr": {
    "nav.about": "À propos",
    "hero.eyebrow": "Agence web à Kassel",
    "hero.title1": "Design et développement web pour votre prochaine étape.",
    "hero.description": "Je crée des sites modernes et des identités numériques pour les entreprises, les indépendants et les créateurs. Un design clair et une technique soignée pour présenter votre offre et faciliter le contact.",
    "hero.trust": "Contact personnel. Engagements clairs. Sites bien pensés.",
    "hero.regions": "À Kassel, avec des contacts en Allemagne et en Suisse.",
    "hero.refBtn": "Découvrir les projets",
    "about.title": "La personne derrière Naser Solutions.",
    "about.description": "Je suis <strong>Yasin Adam Aissani</strong>, fondateur de Naser Solutions à Kassel. Je réunis design et développement pour des sites fidèles aux entreprises et à leurs équipes.",
    "about.training": "Je suis actuellement en reconversion pour devenir spécialiste informatique en développement d'applications. Mes projets et la création de sites me permettent d'approfondir mes apprentissages.",
    "about.swiss": "Mon stage pendant mon séjour d'un an en Suisse a été une étape importante, chez",
    "about.mentor": "est un ami proche et développeur full-stack senior expérimenté. Il m'a initié au code et continue de me soutenir en ami.",
    "about.networkTitle": "Des liens personnels, des progrès partagés.",
    "about.network": "Mon réseau comprend des agences web en Suisse et en Allemagne. À Kassel, je transmets mes connaissances à des amis et connaissances pour collaborer sur des projets adaptés.",
    "about.role": "Fondateur et votre interlocuteur",
    "about.benefit1": "Un échange direct avec votre interlocuteur",
    "about.benefit2": "Une technique adaptée au projet",
    "about.benefit3": "Des étapes claires jusqu'au lancement",
    "about.benefit4": "Un périmètre et un budget convenus",
    "services.title": "Un bon site commence par un plan clair.",
    "services.description": "Nous définissons vos besoins, puis réunissons design, contenu et développement.",
    "services.web.description": "Des sites modernes et adaptatifs, des contenus clairs et une base technique facile à maintenir.",
    "services.supermarket.title": "Applications web pour le commerce",
    "services.supermarket.description": "Des outils pour vos offres, informations clients et processus. Fonctionnalités et faisabilité sont définies ensemble.",
    "services.social.description": "Contenus et concepts visuels pour vos réseaux. Campagnes adaptées au public, au budget et aux objectifs convenus.",
    "services.design.description": "Logos, couleurs et éléments graphiques cohérents pour votre site et vos supports.",
    "services.seo.description": "Structure claire, textes utiles et temps de chargement optimisés pour les visiteurs et les moteurs de recherche.",
    "services.ai.description": "Retouche d'images et montage vidéo, avec l'IA lorsqu'elle soutient utilement la création.",
    "projects.badge": "Travaux sélectionnés",
    "projects.title": "Des idées qui prennent forme.",
    "projects.description": "Sites, design et contenus issus de mon travail. Les projets présentés peuvent encore évoluer.",
    "vision.label": "Ma méthode",
    "vision.title": "Avancer ensemble, étape par étape.",
    "vision.description": "L'expérience pratique, les échanges sincères et le partage font grandir Naser Solutions. Votre projet avance par étapes réalistes.",
    "vision.innovation.title": "Technique adaptée",
    "vision.innovation.description": "Des outils choisis selon vos besoins et la maintenance future.",
    "vision.results.title": "Objectifs clairs",
    "vision.results.description": "Nous définissons les objectifs du site et la manière de les vérifier.",
    "vision.creative.title": "Votre caractère",
    "vision.creative.description": "Design et contenus expriment votre identité et votre offre.",
    "vision.partnership.title": "Échanges directs",
    "vision.partnership.description": "Vous connaissez les intervenants, les prochaines étapes et les décisions à prendre.",
    "tools.title": "Les outils de réalisation",
    "tools.description": "Design, développement et outils d'IA choisis selon les besoins du projet.",
    "contact.title": "Quel est votre projet ?",
    "contact.description": "Parlons de votre idée ou de votre site actuel pour définir le périmètre et les prochaines étapes.",
    "contact.city": "Kassel, Allemagne",
    "contact.form.title": "Parlons de votre projet.",
    "contact.form.intro": "Quelques phrases suffisent. Je vous répondrai personnellement.",
    "contact.form.privacy": "Vos informations servent à répondre à votre demande. Détails :",
    "contact.form.messagePlaceholder": "Vos besoins, votre site actuel, votre calendrier ou votre budget ?",
    "contact.form.success": "Merci pour votre message. Je vous répondrai personnellement.",
    "contact.form.error": "L'envoi n'a pas pu être confirmé. Contactez-moi directement par e-mail.",
    "about.family": "Je suis père d'un garçon depuis fin 2025. Son prénom a inspiré Naser Solutions. Je vis à Kassel depuis décembre 2025 ; auparavant, j'habitais en Bavière avec ma mère et mes frères et sœurs.",
    "about.backgroundTitle": "En savoir plus sur mon parcours",
    "about.school": "J'ai obtenu mon diplôme allemand de fin d'études secondaires intermédiaires en tête de ma classe et j'ai été représentant principal des élèves.",
    "about.bundeswehr": "J'ai brièvement servi dans la Bundeswehr et terminé la formation militaire initiale. Mon grade est Gefreiter ; mon affectation était soldat informatique, avec un rôle secondaire de medic.",
  },
  "es": {
    "nav.about": "Sobre mí",
    "hero.eyebrow": "Agencia web en Kassel",
    "hero.title1": "Diseño y desarrollo web para tu próximo paso.",
    "hero.description": "Creo sitios modernos e identidades digitales para empresas, profesionales y creadores. Diseño claro y tecnología cuidada para explicar tu oferta y facilitar el contacto.",
    "hero.trust": "Contacto personal. Acuerdos claros. Sitios bien pensados.",
    "hero.regions": "Desde Kassel, con contactos en Alemania y Suiza.",
    "hero.refBtn": "Explorar proyectos",
    "about.title": "La persona detrás de Naser Solutions.",
    "about.description": "Soy <strong>Yasin Adam Aissani</strong>, fundador de Naser Solutions en Kassel. Combino diseño y desarrollo para crear sitios acordes con cada empresa y su gente.",
    "about.training": "Actualmente estoy cursando una reconversión profesional como especialista informático en desarrollo de aplicaciones. Profundizo lo aprendido con proyectos propios y trabajo práctico en sitios web.",
    "about.swiss": "Un paso importante fueron mis prácticas durante el año que viví en Suiza, en",
    "about.mentor": "es un buen amigo y desarrollador full-stack sénior con amplia experiencia. Me inició en la programación y sigue apoyándome como amigo.",
    "about.networkTitle": "Conexiones personales, progreso compartido.",
    "about.network": "Mi red incluye agencias web de Suiza y Alemania. En Kassel comparto conocimientos con amigos y conocidos para colaborar en proyectos adecuados.",
    "about.role": "Fundador y tu contacto",
    "about.benefit1": "Comunicación directa con quien lleva tu proyecto",
    "about.benefit2": "Tecnología adecuada a tus necesidades",
    "about.benefit3": "Pasos claros hasta el lanzamiento",
    "about.benefit4": "Alcance y presupuesto acordados",
    "services.title": "Una buena web empieza con un plan claro.",
    "services.description": "Definimos tus necesidades y reunimos diseño, contenido y desarrollo.",
    "services.web.description": "Sitios modernos y adaptables con contenidos claros, navegación sencilla y una base técnica mantenible.",
    "services.supermarket.title": "Aplicaciones web para comercios",
    "services.supermarket.description": "Herramientas para ofertas, información al cliente y procesos comerciales. Acordamos funciones y viabilidad antes de empezar.",
    "services.social.description": "Contenidos y conceptos visuales para tus redes. Campañas adaptadas a tu público, presupuesto y objetivos acordados.",
    "services.design.description": "Logotipos, colores y elementos coherentes para tu web y otros medios.",
    "services.seo.description": "Estructura clara, textos útiles y mejores tiempos de carga para personas y buscadores.",
    "services.ai.description": "Edición de imágenes y vídeo con IA donde aporte al proceso creativo.",
    "projects.badge": "Trabajos seleccionados",
    "projects.title": "Ideas que toman forma.",
    "projects.description": "Sitios, diseño y contenidos de mi trabajo práctico. Los proyectos enlazados pueden seguir evolucionando.",
    "vision.label": "Mi forma de trabajar",
    "vision.title": "Crecer juntos, paso a paso.",
    "vision.description": "Naser Solutions crece con experiencia práctica, conversaciones honestas y conocimiento compartido. Para tu proyecto, eso significa pasos realistas.",
    "vision.innovation.title": "Tecnología adecuada",
    "vision.innovation.description": "Elegimos herramientas según tus necesidades y el mantenimiento futuro.",
    "vision.results.title": "Objetivos claros",
    "vision.results.description": "Definimos qué debe conseguir tu sitio y cómo comprobarlo.",
    "vision.creative.title": "Tu identidad",
    "vision.creative.description": "Diseño y contenido muestran quién eres y qué ofreces.",
    "vision.partnership.title": "Comunicación directa",
    "vision.partnership.description": "Sabes quién trabaja en tu proyecto, los próximos pasos y las decisiones pendientes.",
    "tools.title": "Herramientas para crear",
    "tools.description": "Diseño, desarrollo y herramientas de IA elegidas según las necesidades del proyecto.",
    "contact.title": "¿Qué tienes en mente?",
    "contact.description": "Cuéntame tu idea o háblame de tu sitio actual. Juntos definiremos el alcance y los siguientes pasos.",
    "contact.city": "Kassel, Alemania",
    "contact.form.title": "Hablemos de tu proyecto.",
    "contact.form.intro": "Unas pocas frases bastan. Te responderé personalmente.",
    "contact.form.privacy": "Uso tus datos para responder a tu consulta. Detalles:",
    "contact.form.messagePlaceholder": "¿Qué necesitas? ¿Tienes web, plazos o presupuesto?",
    "contact.form.success": "Gracias por tu mensaje. Te responderé personalmente.",
    "contact.form.error": "No se pudo confirmar el envío. Escríbeme directamente por correo.",
    "about.family": "Soy padre de un niño desde finales de 2025. Su nombre inspiró Naser Solutions. Vivo en Kassel desde diciembre de 2025; antes vivía en Baviera con mi madre y mis hermanos.",
    "about.backgroundTitle": "Más sobre mi trayectoria",
    "about.school": "Terminé la titulación alemana de educación secundaria intermedia como el mejor de mi clase y fui representante principal del alumnado.",
    "about.bundeswehr": "Serví brevemente en la Bundeswehr y completé la instrucción básica. Mi rango es Gefreiter; mi destino era soldado de informática, con función secundaria de medic.",
  },
  "it": {
    "nav.about": "Chi sono",
    "hero.eyebrow": "Agenzia web a Kassel",
    "hero.title1": "Web design e sviluppo per il tuo prossimo passo.",
    "hero.description": "Creo siti moderni e identità digitali per aziende, professionisti e creator. Design chiaro e tecnologia curata per presentare la tua offerta e facilitare i contatti.",
    "hero.trust": "Contatto personale. Accordi chiari. Siti ben progettati.",
    "hero.regions": "A Kassel, con contatti in Germania e Svizzera.",
    "hero.refBtn": "Scopri i progetti",
    "about.title": "La persona dietro Naser Solutions.",
    "about.description": "Sono <strong>Yasin Adam Aissani</strong>, fondatore di Naser Solutions a Kassel. Unisco design e sviluppo per siti in sintonia con le aziende e le loro persone.",
    "about.training": "Sto seguendo un percorso di riqualificazione professionale come specialista informatico nello sviluppo di applicazioni. Approfondisco ciò che imparo con progetti personali e lavoro pratico sui siti.",
    "about.swiss": "Una tappa importante è stato il tirocinio durante il mio soggiorno di un anno in Svizzera presso",
    "about.mentor": "è un caro amico e un senior full-stack developer di lunga esperienza. Mi ha avvicinato alla programmazione e continua a sostenermi come amico.",
    "about.networkTitle": "Legami personali, crescita condivisa.",
    "about.network": "La mia rete comprende agenzie web in Svizzera e Germania. A Kassel condivido le mie conoscenze con amici e conoscenti per collaborare su progetti adatti.",
    "about.role": "Fondatore e tuo referente",
    "about.benefit1": "Contatto diretto con chi segue il progetto",
    "about.benefit2": "Tecnologia adatta alle tue esigenze",
    "about.benefit3": "Passi chiari fino al lancio",
    "about.benefit4": "Ambito e budget concordati",
    "services.title": "Un buon sito parte da un piano chiaro.",
    "services.description": "Definiamo le tue esigenze e uniamo design, contenuti e sviluppo.",
    "services.web.description": "Siti moderni e responsive con contenuti chiari, navigazione semplice e una base tecnica gestibile.",
    "services.supermarket.title": "App web per il commercio",
    "services.supermarket.description": "Strumenti per offerte, informazioni ai clienti e processi commerciali. Concordiamo funzioni e fattibilità prima dello sviluppo.",
    "services.social.description": "Contenuti e idee visive per i social. Campagne in linea con pubblico, budget e obiettivi concordati.",
    "services.design.description": "Loghi, colori ed elementi coerenti per il sito e gli altri mezzi di comunicazione.",
    "services.seo.description": "Struttura chiara, testi utili e tempi di caricamento ottimizzati per utenti e motori di ricerca.",
    "services.ai.description": "Elaborazione di immagini e video, con l'IA dove sostiene concretamente la creatività.",
    "projects.badge": "Lavori selezionati",
    "projects.title": "Idee che prendono forma.",
    "projects.description": "Siti, design e contenuti dal mio lavoro pratico. I progetti collegati possono continuare a evolversi.",
    "vision.label": "Come lavoro",
    "vision.title": "Crescere insieme, passo dopo passo.",
    "vision.description": "Naser Solutions cresce con esperienza pratica, dialogo sincero e conoscenze condivise. Il tuo progetto avanza con passi realistici.",
    "vision.innovation.title": "Tecnologia adatta",
    "vision.innovation.description": "Scegliamo strumenti in base alle esigenze e alla manutenzione futura.",
    "vision.results.title": "Obiettivi chiari",
    "vision.results.description": "Definiamo insieme cosa deve fare il sito e come verificarlo.",
    "vision.creative.title": "La tua identità",
    "vision.creative.description": "Design e contenuti raccontano chi sei e cosa offri.",
    "vision.partnership.title": "Dialogo diretto",
    "vision.partnership.description": "Sai chi lavora al progetto, quali sono i prossimi passi e le decisioni aperte.",
    "tools.title": "Strumenti per realizzare",
    "tools.description": "Design, sviluppo e strumenti di IA scelti in base al progetto.",
    "contact.title": "Cosa hai in mente?",
    "contact.description": "Parlami della tua idea o del sito attuale. Definiremo insieme ambito, possibilità e prossimi passi.",
    "contact.city": "Kassel, Germania",
    "contact.form.title": "Parliamo del tuo progetto.",
    "contact.form.intro": "Bastano poche frasi. Ti risponderò personalmente.",
    "contact.form.privacy": "Uso i tuoi dati per rispondere alla richiesta. Dettagli:",
    "contact.form.messagePlaceholder": "Cosa ti serve? Hai un sito, una scadenza o un budget?",
    "contact.form.success": "Grazie per il messaggio. Ti risponderò personalmente.",
    "contact.form.error": "Invio non confermato. Contattami direttamente via e-mail.",
    "about.family": "Sono padre di un bambino dalla fine del 2025. Il suo nome ha ispirato Naser Solutions. Vivo a Kassel da dicembre 2025; prima abitavo in Baviera con mia madre e i miei fratelli.",
    "about.backgroundTitle": "Il mio percorso",
    "about.school": "Ho concluso il percorso scolastico tedesco della Mittlere Reife come migliore della classe e sono stato il principale rappresentante degli studenti.",
    "about.bundeswehr": "Ho prestato brevemente servizio nella Bundeswehr e completato l'addestramento di base. Il mio grado è Gefreiter; il mio impiego era soldato informatico, con ruolo secondario di medic.",
  },
  "pt": {
    "nav.about": "Sobre mim",
    "hero.eyebrow": "Agência web em Kassel",
    "hero.title1": "Design e desenvolvimento web para o próximo passo.",
    "hero.description": "Crio sites modernos e identidades digitais para empresas, profissionais e criadores. Design claro e tecnologia cuidada para apresentar a sua oferta e facilitar o contacto.",
    "hero.trust": "Contacto pessoal. Acordos claros. Sites bem pensados.",
    "hero.regions": "Em Kassel, com contactos na Alemanha e na Suíça.",
    "hero.refBtn": "Explorar projetos",
    "about.title": "A pessoa por trás da Naser Solutions.",
    "about.description": "Sou <strong>Yasin Adam Aissani</strong>, fundador da Naser Solutions em Kassel. Uno design e desenvolvimento para criar sites adequados a cada empresa e às suas pessoas.",
    "about.training": "Estou em reconversão profissional para especialista de informática em desenvolvimento de aplicações. Aprofundo a aprendizagem através de projetos próprios e trabalho prático em sites.",
    "about.swiss": "Uma etapa importante foi o estágio durante o ano que vivi na Suíça, na",
    "about.mentor": "é um grande amigo e programador full-stack sénior com muitos anos de experiência. Foi quem me iniciou na programação e continua a apoiar-me como amigo.",
    "about.networkTitle": "Ligações pessoais, progresso partilhado.",
    "about.network": "A minha rede inclui agências web na Suíça e na Alemanha. Em Kassel, partilho conhecimentos com amigos e conhecidos para colaborarmos em projetos adequados.",
    "about.role": "Fundador e o seu contacto",
    "about.benefit1": "Contacto direto com quem acompanha o projeto",
    "about.benefit2": "Tecnologia adequada às suas necessidades",
    "about.benefit3": "Etapas claras até ao lançamento",
    "about.benefit4": "Âmbito e orçamento acordados",
    "services.title": "Um bom site começa com um plano claro.",
    "services.description": "Definimos as necessidades e reunimos design, conteúdos e desenvolvimento.",
    "services.web.description": "Sites modernos e adaptáveis, com conteúdos claros, navegação simples e uma base técnica fácil de manter.",
    "services.supermarket.title": "Aplicações web para o comércio",
    "services.supermarket.description": "Ferramentas para ofertas, informação ao cliente e processos comerciais. Funções e viabilidade são acordadas antes do desenvolvimento.",
    "services.social.description": "Conteúdos e conceitos visuais para as redes. Campanhas adequadas ao público, orçamento e objetivos acordados.",
    "services.design.description": "Logótipos, cores e elementos coerentes para o site e outros meios.",
    "services.seo.description": "Estrutura clara, textos úteis e carregamento otimizado para pessoas e motores de pesquisa.",
    "services.ai.description": "Edição de imagem e vídeo, com IA onde contribua para o processo criativo.",
    "projects.badge": "Trabalhos selecionados",
    "projects.title": "Ideias que ganham forma.",
    "projects.description": "Sites, design e conteúdos do meu trabalho prático. Os projetos apresentados podem continuar a evoluir.",
    "vision.label": "Como trabalho",
    "vision.title": "Crescer juntos, passo a passo.",
    "vision.description": "A Naser Solutions cresce com experiência prática, diálogo honesto e conhecimento partilhado. O seu projeto avança com passos realistas.",
    "vision.innovation.title": "Tecnologia adequada",
    "vision.innovation.description": "Escolhemos ferramentas segundo as necessidades e a manutenção futura.",
    "vision.results.title": "Objetivos claros",
    "vision.results.description": "Definimos o que o site deve fazer e como verificar o resultado.",
    "vision.creative.title": "A sua identidade",
    "vision.creative.description": "Design e conteúdos mostram quem é e o que oferece.",
    "vision.partnership.title": "Diálogo direto",
    "vision.partnership.description": "Sabe quem trabalha no projeto, os próximos passos e as decisões pendentes.",
    "tools.title": "Ferramentas para realizar",
    "tools.description": "Design, desenvolvimento e ferramentas de IA escolhidas conforme o projeto.",
    "contact.title": "O que tem em mente?",
    "contact.description": "Conte-me a sua ideia ou fale do seu site atual. Juntos definimos o âmbito e os próximos passos.",
    "contact.city": "Kassel, Alemanha",
    "contact.form.title": "Vamos falar do seu projeto.",
    "contact.form.intro": "Bastam algumas frases. Responderei pessoalmente.",
    "contact.form.privacy": "Uso os seus dados para responder ao pedido. Detalhes:",
    "contact.form.messagePlaceholder": "O que precisa? Já tem site, prazo ou orçamento?",
    "contact.form.success": "Obrigado pela mensagem. Responderei pessoalmente.",
    "contact.form.error": "Não foi possível confirmar o envio. Contacte-me diretamente por e-mail.",
    "about.family": "Sou pai de um menino desde o final de 2025. O seu nome inspirou a Naser Solutions. Vivo em Kassel desde dezembro de 2025; antes vivia na Baviera com a minha mãe e os meus irmãos.",
    "about.backgroundTitle": "Mais sobre o meu percurso",
    "about.school": "Concluí a qualificação escolar alemã Mittlere Reife como o melhor da turma e fui o representante principal dos alunos.",
    "about.bundeswehr": "Servi brevemente na Bundeswehr e concluí a formação militar básica. O meu posto é Gefreiter; a minha função era soldado de informática, com função secundária de medic.",
  },
  "tr": {
    "nav.about": "Hakkımda",
    "hero.eyebrow": "Kassel'de web ajansı",
    "hero.title1": "Bir sonraki adımın için web tasarımı ve geliştirme.",
    "hero.description": "İşletmeler, bağımsız çalışanlar ve içerik üreticileri için modern siteler ve dijital marka kimlikleri geliştiriyorum. Anlaşılır tasarım ve özenli teknolojiyle hizmetlerini tanıtmayı ve iletişimi kolaylaştırıyorum.",
    "hero.trust": "Doğrudan iletişim. Açık anlaşmalar. Özenli web siteleri.",
    "hero.regions": "Kassel merkezli, Almanya ve İsviçre'de bağlantılar.",
    "hero.refBtn": "Projeleri keşfet",
    "about.title": "Naser Solutions'ın arkasındaki kişi.",
    "about.description": "Ben <strong>Yasin Adam Aissani</strong>, Kassel'deki Naser Solutions'ın kurucusuyum. İşletmelere ve insanlarına uygun siteler için tasarım ve geliştirmeyi birleştiriyorum.",
    "about.training": "Şu anda uygulama geliştirme alanında bilişim uzmanı olmak için mesleki yeniden eğitim alıyorum. Öğrendiklerimi kendi projelerim ve web sitesi çalışmalarıyla pekiştiriyorum.",
    "about.swiss": "İsviçre'de yaşadığım bir yıl boyunca yaptığım staj önemli bir adımdı. Staj yaptığım yer:",
    "about.mentor": "yakın arkadaşım ve uzun yıllardır çalışan kıdemli full-stack geliştirici. Beni kodlamayla tanıştırdı ve arkadaşça desteğini sürdürüyor.",
    "about.networkTitle": "Kişisel bağlar, ortak ilerleme.",
    "about.network": "Çevremde İsviçre ve Almanya'dan web ajansları var. Kassel'de uygun projelerde birlikte çalışabilmek için arkadaşlarıma ve tanıdıklarıma bilgilerimi aktarıyorum.",
    "about.role": "Kurucu ve iletişim kişin",
    "about.benefit1": "Projenle ilgilenen kişiyle doğrudan iletişim",
    "about.benefit2": "İhtiyacına uygun teknoloji",
    "about.benefit3": "Fikirden yayına anlaşılır adımlar",
    "about.benefit4": "Birlikte belirlenen kapsam ve bütçe",
    "services.title": "İyi bir site açık bir planla başlar.",
    "services.description": "İhtiyaçlarını belirleyip tasarım, içerik ve geliştirmeyi birleştiriyoruz.",
    "services.web.description": "Açık içerikli, kolay gezilen ve sürdürülebilir teknik temele sahip modern, duyarlı siteler.",
    "services.supermarket.title": "Perakende için web uygulamaları",
    "services.supermarket.description": "Teklifler, müşteri bilgileri ve iş süreçleri için araçlar. Özellikleri ve uygulanabilirliği önceden belirliyoruz.",
    "services.social.description": "Sosyal kanallar için içerik ve görsel konseptler. Hedef kitle, bütçe ve hedeflere uygun kampanyalar.",
    "services.design.description": "Site ve diğer mecralar için uyumlu logolar, renkler ve tasarım öğeleri.",
    "services.seo.description": "İnsanlar ve arama motorları için açık yapı, yararlı metinler ve iyileştirilmiş yükleme süreleri.",
    "services.ai.description": "Yaratıcı sürece katkı sağladığı yerde yapay zekâ destekli görsel ve video düzenleme.",
    "projects.badge": "Seçili çalışmalar",
    "projects.title": "Şekil alan fikirler.",
    "projects.description": "Pratik çalışmalarımdan siteler, tasarımlar ve içerikler. Bağlantılı projeler gelişmeye devam edebilir.",
    "vision.label": "Çalışma biçimim",
    "vision.title": "Adım adım birlikte büyümek.",
    "vision.description": "Naser Solutions deneyim, dürüst iletişim ve bilgi paylaşımıyla büyüyor. Projen için gerçekçi adımlar ve ihtiyaca uygun çözümler sunuyorum.",
    "vision.innovation.title": "Uygun teknoloji",
    "vision.innovation.description": "Araçları ihtiyaçlara ve ilerideki bakıma göre seçiyoruz.",
    "vision.results.title": "Açık hedefler",
    "vision.results.description": "Sitenin amacını ve sonucun nasıl kontrol edileceğini belirliyoruz.",
    "vision.creative.title": "Kendi kimliğin",
    "vision.creative.description": "Tasarım ve içerik kim olduğunu ve ne sunduğunu gösterir.",
    "vision.partnership.title": "Doğrudan iletişim",
    "vision.partnership.description": "Projede kimin çalıştığını, sonraki adımları ve açık kararları bilirsin.",
    "tools.title": "Uygulama araçları",
    "tools.description": "Tasarım, geliştirme ve seçili yapay zekâ araçları projenin ihtiyaçlarına göre kullanılır.",
    "contact.title": "Aklında ne var?",
    "contact.description": "Fikrini veya mevcut siteni anlat. Kapsamı, seçenekleri ve sonraki adımları birlikte belirleyelim.",
    "contact.city": "Kassel, Almanya",
    "contact.form.title": "Projeni konuşalım.",
    "contact.form.intro": "Başlamak için birkaç cümle yeter. Şahsen yanıtlayacağım.",
    "contact.form.privacy": "Bilgilerini talebini yanıtlamak için kullanıyorum. Ayrıntılar:",
    "contact.form.messagePlaceholder": "Neye ihtiyacın var? Siten, takvimin veya bütçen belli mi?",
    "contact.form.success": "Mesajın için teşekkürler. Şahsen dönüş yapacağım.",
    "contact.form.error": "Gönderim doğrulanamadı. Lütfen doğrudan e-posta ile ulaş.",
    "about.family": "2025'in sonundan beri bir oğlum var. Naser Solutions adı onun adından geliyor. Aralık 2025'ten beri Kassel'de yaşıyorum; öncesinde Bavyera'da annem ve kardeşlerimle yaşıyordum.",
    "about.backgroundTitle": "Yolculuğum hakkında",
    "about.school": "Almanya'daki Mittlere Reife diplomamı sınıf birincisi olarak aldım ve okulda birinci öğrenci temsilcisi olarak görev yaptım.",
    "about.bundeswehr": "Kısa süre Alman Bundeswehr'de görev yapıp temel eğitimi tamamladım. Rütbem Gefreiter; görevim IT askeri, ikincil görevim medic idi.",
  },
  "sq": {
    "nav.about": "Rreth meje",
    "hero.eyebrow": "Agjenci web në Kassel",
    "hero.title1": "Dizajn dhe zhvillim web për hapin tënd të radhës.",
    "hero.description": "Krijoj faqe moderne dhe identitete digjitale për biznese, profesionistë të pavarur dhe krijues. Dizajn i qartë dhe teknologji e menduar për të prezantuar ofertën dhe lehtësuar kontaktin.",
    "hero.trust": "Kontakt personal. Marrëveshje të qarta. Faqe të menduara mirë.",
    "hero.regions": "Në Kassel, me kontakte në Gjermani dhe Zvicër.",
    "hero.refBtn": "Shiko projektet",
    "about.title": "Njeriu pas Naser Solutions.",
    "about.description": "Jam <strong>Yasin Adam Aissani</strong>, themelues i Naser Solutions në Kassel. Bashkoj dizajnin dhe zhvillimin për faqe që u përshtaten bizneseve dhe njerëzve të tyre.",
    "about.training": "Aktualisht po ndjek rikualifikim profesional si specialist IT për zhvillim aplikacionesh. I thelloj njohuritë me projekte personale dhe punë praktike në faqe web.",
    "about.swiss": "Një hap i rëndësishëm ishte praktika gjatë qëndrimit tim njëvjeçar në Zvicër te",
    "about.mentor": "është mik i afërt dhe zhvillues senior full-stack me përvojë shumëvjeçare. Ai më prezantoi me programimin dhe vazhdon të më mbështesë si mik.",
    "about.networkTitle": "Lidhje personale, përparim i përbashkët.",
    "about.network": "Rrjeti im përfshin agjenci web në Zvicër dhe Gjermani. Në Kassel ndaj njohuritë me miq e të njohur që të bashkëpunojmë në projekte të përshtatshme.",
    "about.role": "Themelues dhe kontakti yt",
    "about.benefit1": "Kontakt i drejtpërdrejtë për projektin",
    "about.benefit2": "Teknologji që i përshtatet nevojës",
    "about.benefit3": "Hapa të qartë deri në publikim",
    "about.benefit4": "Fushëveprim dhe buxhet të dakordësuar",
    "services.title": "Një faqe e mirë nis me plan të qartë.",
    "services.description": "Përcaktojmë nevojat dhe bashkojmë dizajnin, përmbajtjen dhe zhvillimin.",
    "services.web.description": "Faqe moderne e të përshtatshme për pajisje të ndryshme, me përmbajtje të qartë dhe bazë teknike të mirëmbajtshme.",
    "services.supermarket.title": "Aplikacione web për tregtinë",
    "services.supermarket.description": "Mjete për oferta, informacion për klientët dhe procese tregtare. Funksionet dhe realizueshmërinë i dakordësojmë paraprakisht.",
    "services.social.description": "Përmbajtje dhe koncepte vizuale për rrjetet sociale. Fushata sipas audiencës, buxhetit dhe objektivave.",
    "services.design.description": "Logo, ngjyra dhe elemente të harmonizuara për faqen dhe mediat e tua.",
    "services.seo.description": "Strukturë e qartë, tekste të dobishme dhe ngarkim i optimizuar për njerëzit dhe motorët e kërkimit.",
    "services.ai.description": "Përpunim imazhesh dhe videosh, me IA aty ku ndihmon krijimtarinë.",
    "projects.badge": "Punë të zgjedhura",
    "projects.title": "Ide që marrin formë.",
    "projects.description": "Faqe, dizajn dhe përmbajtje nga puna ime praktike. Projektet e lidhura mund të vazhdojnë të zhvillohen.",
    "vision.label": "Si punoj",
    "vision.title": "Të rritemi bashkë, hap pas hapi.",
    "vision.description": "Naser Solutions rritet me përvojë praktike, biseda të sinqerta dhe ndarje njohurish. Projekti yt ecën me hapa realistë.",
    "vision.innovation.title": "Teknologji e përshtatshme",
    "vision.innovation.description": "Zgjedhim mjete sipas nevojave dhe mirëmbajtjes së ardhshme.",
    "vision.results.title": "Objektiva të qarta",
    "vision.results.description": "Përcaktojmë çfarë duhet të bëjë faqja dhe si ta verifikojmë.",
    "vision.creative.title": "Identiteti yt",
    "vision.creative.description": "Dizajni dhe përmbajtja tregojnë kush je dhe çfarë ofron.",
    "vision.partnership.title": "Komunikim i drejtpërdrejtë",
    "vision.partnership.description": "E di kush punon në projekt, hapat e ardhshëm dhe vendimet e hapura.",
    "tools.title": "Mjete për realizimin",
    "tools.description": "Dizajn, zhvillim dhe mjete IA të zgjedhura sipas nevojave të projektit.",
    "contact.title": "Çfarë ke në mendje?",
    "contact.description": "Më trego për idenë ose faqen aktuale. Së bashku përcaktojmë mundësitë dhe hapat e radhës.",
    "contact.city": "Kassel, Gjermani",
    "contact.form.title": "Le të flasim për projektin tënd.",
    "contact.form.intro": "Mjaftojnë disa fjali. Do të përgjigjem personalisht.",
    "contact.form.privacy": "Të dhënat i përdor për t'iu përgjigjur kërkesës. Hollësi:",
    "contact.form.messagePlaceholder": "Çfarë të duhet? Ke faqe, afat apo buxhet?",
    "contact.form.success": "Faleminderit për mesazhin. Do të të përgjigjem personalisht.",
    "contact.form.error": "Dërgimi nuk u konfirmua. Më kontakto drejtpërdrejt me email.",
    "about.family": "Jam baba i një djali që nga fundi i vitit 2025. Emri i tij frymëzoi Naser Solutions. Jetoj në Kassel që nga dhjetori 2025; më parë jetoja në Bavari me nënën dhe motrat e vëllezërit.",
    "about.backgroundTitle": "Më shumë për rrugëtimin tim",
    "about.school": "Përfundova kualifikimin shkollor gjerman Mittlere Reife si më i miri i klasës dhe isha përfaqësuesi kryesor i nxënësve.",
    "about.bundeswehr": "Shërbeva shkurt në Bundeswehr dhe përfundova trajnimin bazë. Grada ime është Gefreiter; detyra ime ishte ushtar IT, me rol dytësor medic.",
  },
  "ru": {
    "nav.about": "Обо мне",
    "hero.eyebrow": "Веб-агентство в Касселе",
    "hero.title1": "Веб-дизайн и разработка для вашего следующего шага.",
    "hero.description": "Я создаю современные сайты и цифровой образ бренда для компаний, специалистов и авторов. Понятный дизайн и продуманная разработка помогают представить ваше предложение и упростить связь.",
    "hero.trust": "Личный контакт. Чёткие договорённости. Продуманные сайты.",
    "hero.regions": "В Касселе, с контактами в Германии и Швейцарии.",
    "hero.refBtn": "Посмотреть проекты",
    "about.title": "Человек за Naser Solutions.",
    "about.description": "Я <strong>Yasin Adam Aissani</strong>, основатель Naser Solutions в Касселе. Объединяю дизайн и разработку, чтобы сайты соответствовали бизнесу и его людям.",
    "about.training": "Сейчас я прохожу профессиональную переподготовку на IT-специалиста по разработке приложений. Закрепляю знания в собственных проектах и практической работе над сайтами.",
    "about.swiss": "Важным этапом стала стажировка во время моего годичного проживания в Швейцарии в",
    "about.mentor": "— близкий друг и опытный senior full-stack разработчик. Он познакомил меня с программированием и продолжает поддерживать по-дружески.",
    "about.networkTitle": "Личные связи, совместное развитие.",
    "about.network": "В моём кругу есть веб-агентства Швейцарии и Германии. В Касселе я делюсь знаниями с друзьями и знакомыми, чтобы вместе работать над подходящими проектами.",
    "about.role": "Основатель и ваш контакт",
    "about.benefit1": "Прямое общение с исполнителем",
    "about.benefit2": "Технологии под ваши задачи",
    "about.benefit3": "Понятные шаги до запуска",
    "about.benefit4": "Согласованные объём работ и бюджет",
    "services.title": "Хороший сайт начинается с ясного плана.",
    "services.description": "Определяем потребности и объединяем дизайн, контент и разработку.",
    "services.web.description": "Современные адаптивные сайты с понятным контентом, простой навигацией и удобной поддержкой.",
    "services.supermarket.title": "Веб-приложения для торговли",
    "services.supermarket.description": "Инструменты для предложений, информации покупателям и рабочих процессов. Функции и реализуемость обсуждаем заранее.",
    "services.social.description": "Контент и визуальные концепции для соцсетей. Кампании с учётом аудитории, бюджета и согласованных целей.",
    "services.design.description": "Согласованные логотипы, цвета и графические элементы для сайта и других каналов.",
    "services.seo.description": "Понятная структура, полезные тексты и оптимизация загрузки для людей и поисковых систем.",
    "services.ai.description": "Обработка изображений и видео с ИИ там, где он помогает творческому процессу.",
    "projects.badge": "Избранные работы",
    "projects.title": "Идеи обретают форму.",
    "projects.description": "Сайты, дизайн и контент из моей практики. Проекты по ссылкам могут продолжать развиваться.",
    "vision.label": "Как я работаю",
    "vision.title": "Растём вместе, шаг за шагом.",
    "vision.description": "Naser Solutions развивается благодаря практике, честному общению и обмену знаниями. Для вашего проекта это означает реалистичные шаги.",
    "vision.innovation.title": "Подходящие технологии",
    "vision.innovation.description": "Выбираем инструменты под задачи и будущую поддержку.",
    "vision.results.title": "Ясные цели",
    "vision.results.description": "Определяем задачи сайта и способ проверки результата.",
    "vision.creative.title": "Ваш характер",
    "vision.creative.description": "Дизайн и контент показывают, кто вы и что предлагаете.",
    "vision.partnership.title": "Прямое общение",
    "vision.partnership.description": "Вы знаете, кто работает над проектом, что дальше и какие решения предстоят.",
    "tools.title": "Инструменты для работы",
    "tools.description": "Дизайн, разработка и выбранные инструменты ИИ под потребности проекта.",
    "contact.title": "Что вы планируете?",
    "contact.description": "Расскажите об идее или текущем сайте. Вместе определим объём, возможности и дальнейшие шаги.",
    "contact.city": "Кассель, Германия",
    "contact.form.title": "Обсудим ваш проект.",
    "contact.form.intro": "Для начала достаточно нескольких предложений. Отвечу лично.",
    "contact.form.privacy": "Использую ваши данные для ответа на запрос. Подробнее:",
    "contact.form.messagePlaceholder": "Что вам нужно? Есть ли сайт, сроки или бюджет?",
    "contact.form.success": "Спасибо за сообщение. Я отвечу лично.",
    "contact.form.error": "Отправку не удалось подтвердить. Напишите мне напрямую по электронной почте.",
    "about.family": "В конце 2025 года у меня родился сын. Его имя легло в основу названия Naser Solutions. С декабря 2025 года я живу в Касселе; раньше жил в Баварии с мамой, братьями и сёстрами.",
    "about.backgroundTitle": "Подробнее о моём пути",
    "about.school": "Я получил немецкий школьный аттестат Mittlere Reife лучшим в классе и был главным представителем учеников.",
    "about.bundeswehr": "Я недолго служил в Бундесвере и завершил базовую подготовку. Моё звание — Gefreiter; назначение — IT-солдат, с дополнительной ролью medic.",
  },
  "el": {
    "nav.about": "Σχετικά με εμένα",
    "hero.eyebrow": "Web agency στο Kassel",
    "hero.title1": "Σχεδιασμός και ανάπτυξη web για το επόμενο βήμα σου.",
    "hero.description": "Δημιουργώ σύγχρονες ιστοσελίδες και ψηφιακές ταυτότητες για επιχειρήσεις, επαγγελματίες και δημιουργούς. Καθαρός σχεδιασμός και προσεγμένη τεχνολογία για κατανοητή παρουσίαση και εύκολη επικοινωνία.",
    "hero.trust": "Προσωπική επαφή. Σαφείς συμφωνίες. Προσεγμένες ιστοσελίδες.",
    "hero.regions": "Στο Kassel, με επαφές στη Γερμανία και την Ελβετία.",
    "hero.refBtn": "Δες τα έργα",
    "about.title": "Ο άνθρωπος πίσω από τη Naser Solutions.",
    "about.description": "Είμαι ο <strong>Yasin Adam Aissani</strong>, ιδρυτής της Naser Solutions στο Kassel. Συνδυάζω σχεδιασμό και ανάπτυξη για ιστοσελίδες που ταιριάζουν σε κάθε επιχείρηση.",
    "about.training": "Αυτή την περίοδο παρακολουθώ επαγγελματική επανεκπαίδευση ως ειδικός πληροφορικής στην ανάπτυξη εφαρμογών. Εμβαθύνω μέσα από δικά μου έργα και πρακτική δουλειά σε ιστοσελίδες.",
    "about.swiss": "Σημαντικό βήμα ήταν η πρακτική μου κατά την ετήσια διαμονή μου στην Ελβετία στην",
    "about.mentor": "είναι καλός φίλος και έμπειρος senior full-stack developer. Με έφερε στον προγραμματισμό και συνεχίζει να με στηρίζει φιλικά.",
    "about.networkTitle": "Προσωπικές σχέσεις, κοινή πρόοδος.",
    "about.network": "Το δίκτυό μου περιλαμβάνει web agencies στην Ελβετία και τη Γερμανία. Στο Kassel μοιράζομαι γνώσεις με φίλους και γνωστούς για συνεργασία σε κατάλληλα έργα.",
    "about.role": "Ιδρυτής και υπεύθυνος επικοινωνίας",
    "about.benefit1": "Άμεση επαφή με τον άνθρωπο του έργου",
    "about.benefit2": "Τεχνολογία για τις ανάγκες σου",
    "about.benefit3": "Σαφή βήματα μέχρι τη δημοσίευση",
    "about.benefit4": "Συμφωνημένο εύρος και κόστος",
    "services.title": "Μια καλή ιστοσελίδα ξεκινά με σαφές πλάνο.",
    "services.description": "Ορίζουμε τις ανάγκες και συνδυάζουμε σχεδιασμό, περιεχόμενο και ανάπτυξη.",
    "services.web.description": "Σύγχρονες προσαρμοστικές ιστοσελίδες με σαφές περιεχόμενο, εύκολη πλοήγηση και συντηρήσιμη τεχνική βάση.",
    "services.supermarket.title": "Web εφαρμογές για το εμπόριο",
    "services.supermarket.description": "Εργαλεία για προσφορές, πληροφορίες πελατών και διαδικασίες. Συμφωνούμε λειτουργίες και εφικτότητα εκ των προτέρων.",
    "services.social.description": "Περιεχόμενο και οπτικές ιδέες για τα δίκτυά σου. Καμπάνιες ανάλογα με κοινό, προϋπολογισμό και στόχους.",
    "services.design.description": "Συνεπή λογότυπα, χρώματα και γραφικά για την ιστοσελίδα και τα μέσα σου.",
    "services.seo.description": "Σαφής δομή, χρήσιμα κείμενα και καλύτεροι χρόνοι φόρτωσης για ανθρώπους και μηχανές αναζήτησης.",
    "services.ai.description": "Επεξεργασία εικόνας και βίντεο, με ΤΝ όπου βοηθά τη δημιουργική εργασία.",
    "projects.badge": "Επιλεγμένες δουλειές",
    "projects.title": "Ιδέες που παίρνουν μορφή.",
    "projects.description": "Ιστοσελίδες, σχεδιασμός και περιεχόμενο από την πρακτική δουλειά μου. Τα έργα μπορεί να συνεχίζουν να εξελίσσονται.",
    "vision.label": "Πώς δουλεύω",
    "vision.title": "Μεγαλώνουμε μαζί, βήμα βήμα.",
    "vision.description": "Η Naser Solutions εξελίσσεται με εμπειρία, ειλικρινή επικοινωνία και κοινή γνώση. Για το έργο σου αυτό σημαίνει ρεαλιστικά βήματα.",
    "vision.innovation.title": "Κατάλληλη τεχνολογία",
    "vision.innovation.description": "Επιλέγουμε εργαλεία με βάση τις ανάγκες και τη μελλοντική συντήρηση.",
    "vision.results.title": "Σαφείς στόχοι",
    "vision.results.description": "Ορίζουμε τι πρέπει να κάνει η σελίδα και πώς θα το ελέγξουμε.",
    "vision.creative.title": "Ο χαρακτήρας σου",
    "vision.creative.description": "Σχεδιασμός και περιεχόμενο δείχνουν ποιος είσαι και τι προσφέρεις.",
    "vision.partnership.title": "Άμεση επικοινωνία",
    "vision.partnership.description": "Ξέρεις ποιος εργάζεται, ποια βήματα ακολουθούν και ποιες αποφάσεις εκκρεμούν.",
    "tools.title": "Εργαλεία υλοποίησης",
    "tools.description": "Σχεδιασμός, ανάπτυξη και επιλεγμένα εργαλεία ΤΝ σύμφωνα με τις ανάγκες του έργου.",
    "contact.title": "Τι έχεις στο μυαλό σου;",
    "contact.description": "Πες μου για την ιδέα ή την υπάρχουσα σελίδα σου. Θα ορίσουμε μαζί το εύρος και τα επόμενα βήματα.",
    "contact.city": "Kassel, Γερμανία",
    "contact.form.title": "Ας μιλήσουμε για το έργο σου.",
    "contact.form.intro": "Λίγες προτάσεις αρκούν. Θα απαντήσω προσωπικά.",
    "contact.form.privacy": "Χρησιμοποιώ τα στοιχεία σου για να απαντήσω στο αίτημα. Λεπτομέρειες:",
    "contact.form.messagePlaceholder": "Τι χρειάζεσαι; Υπάρχει σελίδα, προθεσμία ή προϋπολογισμός;",
    "contact.form.success": "Ευχαριστώ για το μήνυμα. Θα απαντήσω προσωπικά.",
    "contact.form.error": "Η αποστολή δεν επιβεβαιώθηκε. Επικοινώνησε απευθείας με email.",
    "about.family": "Είμαι πατέρας ενός γιου από τα τέλη του 2025. Το όνομά του ενέπνευσε τη Naser Solutions. Ζω στο Kassel από τον Δεκέμβριο του 2025· πριν έμενα στη Βαυαρία με τη μητέρα και τα αδέλφια μου.",
    "about.backgroundTitle": "Περισσότερα για την πορεία μου",
    "about.school": "Ολοκλήρωσα τον γερμανικό σχολικό τίτλο Mittlere Reife ως πρώτος στην τάξη και ήμουν ο κύριος εκπρόσωπος των μαθητών.",
    "about.bundeswehr": "Υπηρέτησα για λίγο στη Bundeswehr και ολοκλήρωσα τη βασική εκπαίδευση. Ο βαθμός μου είναι Gefreiter· η ειδικότητά μου ήταν στρατιώτης πληροφορικής, με δευτερεύοντα ρόλο medic.",
  },
  "ar": {
    "nav.about": "عني",
    "hero.eyebrow": "وكالة ويب في كاسل",
    "hero.title1": "تصميم وتطوير مواقع لخطوتك القادمة.",
    "hero.description": "أطوّر مواقع حديثة وهويات رقمية للشركات والمستقلين وصنّاع المحتوى. تصميم واضح وتقنية مدروسة لعرض خدماتك وتسهيل التواصل معك.",
    "hero.trust": "تواصل شخصي. اتفاقات واضحة. مواقع مدروسة.",
    "hero.regions": "من كاسل، مع علاقات في ألمانيا وسويسرا.",
    "hero.refBtn": "اكتشف المشاريع",
    "about.title": "الشخص وراء Naser Solutions.",
    "about.description": "أنا <strong>Yasin Adam Aissani</strong>، مؤسس Naser Solutions في كاسل. أجمع بين التصميم والتطوير لإنشاء مواقع تناسب الشركات والأشخاص وراءها.",
    "about.training": "أتابع حاليًا برنامج إعادة تأهيل مهني لأصبح متخصصًا في تقنية المعلومات وتطوير التطبيقات. أعمّق ما أتعلمه من خلال مشاريعي والعمل العملي على المواقع.",
    "about.swiss": "كانت فترة تدريبي خلال إقامتي لمدة عام في سويسرا خطوة مهمة، لدى",
    "about.mentor": "صديق مقرّب ومطوّر أول شامل بخبرة طويلة. هو من عرّفني على البرمجة، وما زال يدعمني كصديق.",
    "about.networkTitle": "علاقات شخصية وتقدّم مشترك.",
    "about.network": "تضم شبكة معارفي وكالات ويب في سويسرا وألمانيا. وفي كاسل أشارك معرفتي مع الأصدقاء والمعارف لنتعاون في المشاريع المناسبة.",
    "about.role": "المؤسس وجهة تواصلك",
    "about.benefit1": "تواصل مباشر مع المسؤول عن مشروعك",
    "about.benefit2": "تقنية تناسب احتياجاتك",
    "about.benefit3": "خطوات واضحة من الفكرة إلى الإطلاق",
    "about.benefit4": "نطاق وميزانية متفق عليهما",
    "services.title": "الموقع الجيد يبدأ بخطة واضحة.",
    "services.description": "نحدد احتياجاتك ونجمع التصميم والمحتوى والتطوير في حل مناسب.",
    "services.web.description": "مواقع حديثة ومتجاوبة بمحتوى واضح وتصفح بسيط وأساس تقني قابل للصيانة.",
    "services.supermarket.title": "تطبيقات ويب للتجارة",
    "services.supermarket.description": "أدوات للعروض ومعلومات العملاء وإجراءات العمل. نتفق مسبقًا على الوظائف وإمكانية تنفيذها.",
    "services.social.description": "محتوى وأفكار بصرية لقنواتك الاجتماعية، وحملات تناسب الجمهور والميزانية والأهداف المتفق عليها.",
    "services.design.description": "شعارات وألوان وعناصر متناسقة لموقعك ووسائطك الأخرى.",
    "services.seo.description": "هيكل واضح ونصوص مفيدة وتحسين سرعة التحميل ليسهل فهم عرضك على الناس ومحركات البحث.",
    "services.ai.description": "تحرير صور وفيديو مع استخدام الذكاء الاصطناعي عندما يدعم العمل الإبداعي.",
    "projects.badge": "أعمال مختارة",
    "projects.title": "أفكار تأخذ شكلًا.",
    "projects.description": "مواقع وتصاميم ومحتوى من عملي التطبيقي. قد تستمر المشاريع المرتبطة في التطور.",
    "vision.label": "طريقة عملي",
    "vision.title": "ننمو معًا، خطوة بخطوة.",
    "vision.description": "تنمو Naser Solutions بالخبرة العملية والحوار الصادق وتبادل المعرفة. وهذا يعني لمشروعك خطوات واقعية وحلولًا تناسب احتياجاتك.",
    "vision.innovation.title": "تقنية مناسبة",
    "vision.innovation.description": "نختار الأدوات وفق احتياجاتك والصيانة المستقبلية.",
    "vision.results.title": "أهداف واضحة",
    "vision.results.description": "نحدد ما يجب أن يحققه الموقع وكيف نتحقق من النتيجة.",
    "vision.creative.title": "هويتك الخاصة",
    "vision.creative.description": "يوضح التصميم والمحتوى من أنت وما الذي تقدمه.",
    "vision.partnership.title": "حوار مباشر",
    "vision.partnership.description": "تعرف من يعمل على مشروعك والخطوات القادمة والقرارات المفتوحة.",
    "tools.title": "أدوات التنفيذ",
    "tools.description": "تصميم وتطوير وأدوات ذكاء اصطناعي مختارة بحسب احتياجات المشروع.",
    "contact.title": "ما الذي تخطط له؟",
    "contact.description": "أخبرني بفكرتك أو موقعك الحالي. نحدد معًا النطاق والإمكانات والخطوات التالية.",
    "contact.city": "كاسل، ألمانيا",
    "contact.form.title": "لنتحدث عن مشروعك.",
    "contact.form.intro": "تكفي بضع جمل للبدء. سأرد عليك شخصيًا.",
    "contact.form.privacy": "أستخدم بياناتك للرد على طلبك. التفاصيل:",
    "contact.form.messagePlaceholder": "ماذا تحتاج؟ هل لديك موقع أو جدول زمني أو ميزانية؟",
    "contact.form.success": "شكرًا لرسالتك. سأرد عليك شخصيًا.",
    "contact.form.error": "تعذر تأكيد الإرسال. يرجى التواصل معي مباشرة بالبريد الإلكتروني.",
    "about.family": "أصبحت أبًا لولد في أواخر عام 2025، ومن اسمه جاء اسم Naser Solutions. أعيش في كاسل منذ ديسمبر 2025، وقبل ذلك كنت أعيش في بافاريا مع والدتي وإخوتي.",
    "about.backgroundTitle": "المزيد عن مسيرتي",
    "about.school": "أنهيت شهادة Mittlere Reife الألمانية كأفضل طالب في صفي، وشغلت أيضًا منصب الممثل الأول للطلاب.",
    "about.bundeswehr": "خدمت لفترة قصيرة في الجيش الألماني وأكملت التدريب الأساسي. رتبتي Gefreiter، وكان تخصصي جندي تقنية معلومات مع دور ثانوي بصفة medic.",
  },
  "zh": {
    "nav.about": "关于我",
    "hero.eyebrow": "卡塞尔的网站工作室",
    "hero.title1": "网站设计与开发，助你迈出下一步。",
    "hero.description": "我为企业、独立从业者和创作者打造现代网站与数字品牌形象。通过清晰的设计和周到的开发，让人们了解你的服务并轻松联系你。",
    "hero.trust": "直接沟通，明确约定，用心建站。",
    "hero.regions": "立足卡塞尔，与德国和瑞士的同行保持联系。",
    "hero.refBtn": "浏览项目",
    "about.title": "Naser Solutions 背后的人。",
    "about.description": "我是 <strong>Yasin Adam Aissani</strong>，Naser Solutions 在卡塞尔的创始人。我结合设计与开发，为企业及其团队打造合适的网站。",
    "about.training": "我目前正在参加应用开发方向的 IT 专业转岗培训，通过个人项目和实际网站工作深化所学知识。",
    "about.swiss": "在瑞士居住一年的经历中，一段重要的实习让我受益良多，实习机构是",
    "about.mentor": "是我的好友，也是一位经验丰富的资深全栈开发者。他最初带我接触编程，至今仍以朋友的身份支持我。",
    "about.networkTitle": "真诚联系，共同进步。",
    "about.network": "我的人脉包括瑞士和德国的网站工作室。在卡塞尔，我与朋友和熟人分享知识，以便共同承接适合的项目。",
    "about.role": "创始人及你的联系人",
    "about.benefit1": "直接与项目负责人沟通",
    "about.benefit2": "根据需求选择技术",
    "about.benefit3": "从构想到上线的清晰步骤",
    "about.benefit4": "共同商定范围与预算",
    "services.title": "好网站始于清晰的计划。",
    "services.description": "先明确需求，再结合设计、内容与开发提供合适的方案。",
    "services.web.description": "现代响应式网站，配备清晰内容、简洁导航和便于维护的技术基础。",
    "services.supermarket.title": "零售网络应用",
    "services.supermarket.description": "面向促销、客户信息及零售流程的定制工具。开发前共同明确功能和可行性。",
    "services.social.description": "为社交平台制作内容和视觉方案，按受众、预算与约定目标规划推广活动。",
    "services.design.description": "协调统一的标志、色彩和设计元素，用于网站及其他媒体。",
    "services.seo.description": "清晰结构、实用文案和更快加载，帮助访客与搜索引擎理解你的服务。",
    "services.ai.description": "网站和社交媒体的图片与视频编辑，在确有帮助时使用人工智能辅助创作。",
    "projects.badge": "精选作品",
    "projects.title": "让想法逐渐成形。",
    "projects.description": "来自实际工作的网站、设计与内容。链接中的项目可能仍在持续完善。",
    "vision.label": "我的工作方式",
    "vision.title": "携手前进，逐步成长。",
    "vision.description": "Naser Solutions 通过实践、坦诚交流和知识分享不断成长。你的项目也将以务实的步骤推进。",
    "vision.innovation.title": "合适的技术",
    "vision.innovation.description": "根据需求与后续维护选择工具。",
    "vision.results.title": "明确的目标",
    "vision.results.description": "共同确定网站需要实现什么，以及如何检验结果。",
    "vision.creative.title": "独特的个性",
    "vision.creative.description": "设计与内容呈现你的身份和服务特点。",
    "vision.partnership.title": "直接的交流",
    "vision.partnership.description": "你了解项目由谁负责、接下来的步骤和待定事项。",
    "tools.title": "实现想法的工具",
    "tools.description": "按项目需要选择设计、开发与人工智能工具。",
    "contact.title": "你有什么计划？",
    "contact.description": "告诉我你的想法或现有网站情况，我们一起确定范围、可能性与下一步。",
    "contact.city": "德国卡塞尔",
    "contact.form.title": "聊聊你的项目吧。",
    "contact.form.intro": "几句话即可开始，我会亲自回复。",
    "contact.form.privacy": "你的信息将用于回复咨询。详情：",
    "contact.form.messagePlaceholder": "你需要什么？是否已有网站、时间计划或预算？",
    "contact.form.success": "感谢你的留言，我会亲自回复。",
    "contact.form.error": "无法确认消息已发送，请直接通过电子邮件联系我。",
    "about.family": "2025 年底，我成为了一名男孩的父亲。Naser Solutions 的名字来自他的名字。自 2025 年 12 月起，我住在卡塞尔；此前，我与母亲及兄弟姐妹住在巴伐利亚。",
    "about.backgroundTitle": "了解我的经历",
    "about.school": "我以班级第一的成绩取得德国 Mittlere Reife 中等教育毕业资格，并担任过首席学生代表。",
    "about.bundeswehr": "我曾短期服役于德国联邦国防军并完成基础训练，军衔为 Gefreiter，任职方向为 IT 士兵，兼任 medic 角色。",
  }
} satisfies Record<Language, Record<string, string>>
