export const thaiCopy: Record<string, string> = {
  "nav.services": "บริการ",
  "nav.projects": "โปรเจกต์",
  "nav.vision": "แนวทางการทำงาน",
  "nav.contact": "ติดต่อ",
  "language.select": "เลือกภาษา",
  "hero.badge": "ก่อตั้งในปี 2026",
  "hero.subtitle": "เราคิด ออกแบบ และพัฒนา",
  "hero.title2": "ที่ช่วยให้คุณเป็นที่รู้จักและเพิ่มยอดขาย",
  "hero.cta": "เริ่มโปรเจกต์",
  "hero.cta2": "ปรึกษาเบื้องต้นฟรี",
  "hero.vision": "วิสัยทัศน์ของเรา",
  "hero.languages": "เยอรมันและอังกฤษคล่องแคล่ว · อาหรับและฝรั่งเศสระดับมืออาชีพ",
  "stats.founded": "ก่อตั้ง",
  "stats.potential": "ศักยภาพ",
  "stats.passion": "ความมุ่งมั่น",
  "stats.availability": "การติดต่อ",
  "services.label": "บริการ",
  "services.ai.title": "ตัดต่อวิดีโอและภาพด้วย AI",
  "projects.preview": "มีตัวอย่างให้ดูออนไลน์",
  "projects.viewProject": "ดูโปรเจกต์",
  "projects.moreComingSoon": "โปรเจกต์ใหม่กำลังจะตามมา...",
  "projects.crypto.title": "พอร์ทัลข่าวคริปโต",
  "projects.crypto.description": "พอร์ทัลข่าวคริปโตสมัยใหม่ พร้อมอัปเดตแบบเรียลไทม์ วิเคราะห์ตลาด และข่าวในวงการ",
  "projects.studio.title": "Studio Glacé",
  "projects.studio.description": "เว็บไซต์พอร์ตโฟลิโอที่เรียบหรูสำหรับสตูดิโอออกแบบสร้างสรรค์ ด้วยสไตล์มินิมอลและแอนิเมชันที่ลื่นไหล",
  "projects.joesgarage.title": "Joe's Garage Kassel",
  "projects.joesgarage.description": "เว็บไซต์สมัยใหม่สำหรับ Joe's Garage บาร์ร็อกชื่อดังในคัสเซิล ถ่ายทอดบรรยากาศของบาร์พร้อมข้อมูลเครื่องดื่ม กิจกรรม ดนตรีสด การชมถ่ายทอดสดร่วมกัน แกลเลอรี เวลาเปิด และเส้นทาง",
  "projects.luxury.title": "AWD Shop",
  "projects.luxury.description": "ร้านแฟชั่นออนไลน์ระดับพรีเมียมที่ออกแบบทันสมัยและใช้งานสะดวก",
  "projects.donation.title": "เว็บไซต์บริจาค Al Salam",
  "projects.donation.description": "เว็บไซต์บริจาคเพื่อมนุษยธรรมที่ออกแบบทันสมัย พร้อมระบบจัดการการบริจาคที่ใช้งานง่าย",
  "projects.hazechill.title": "Haze & Chill Cafe",
  "projects.hazechill.description": "ออกแบบและดูแลโซเชียลมีเดียสำหรับคาเฟ่ ตั้งแต่ภาพลักษณ์แบรนด์จนถึง Instagram รวมถึงออกแบบเมนู ติดต่อพันธมิตรโฆษณา และสนับสนุนการพัฒนาและขยายแนวคิด",
  "projects.reel.title": "Haze & Chill Café – ผลิตคอนเทนต์",
  "projects.reel.description": "ผลงานนี้เป็นส่วนหนึ่งของการสร้างคอนเทนต์ให้ Haze & Chill Café เราพัฒนาและผลิต Reels และภาพสำหรับ Instagram ของแบรนด์",
  "tools.badge": "เทคโนโลยีที่ใช้",
  "contact.label": "ติดต่อ",
  "contact.email": "อีเมล",
  "contact.phone": "โทรศัพท์",
  "contact.location": "ที่ตั้ง",
  "contact.whatsapp": "ติดต่อโดยตรงผ่าน WhatsApp",
  "contact.form.name": "ชื่อ *",
  "contact.form.namePlaceholder": "ชื่อของคุณ",
  "contact.form.email": "อีเมล *",
  "contact.form.emailPlaceholder": "you@email.com",
  "contact.form.phone": "โทรศัพท์ (ไม่จำเป็น)",
  "contact.form.phonePlaceholder": "+66 81 234 5678",
  "contact.form.message": "ข้อความ *",
  "contact.form.submit": "ส่งข้อความ",
  "contact.form.sending": "กำลังส่ง...",
  "footer.imprint": "ข้อมูลผู้ให้บริการ",
  "footer.privacy": "ความเป็นส่วนตัว",
  "footer.agb": "เงื่อนไขการให้บริการ",
  "footer.rights": "สงวนลิขสิทธิ์",
  "modal.backToSite": "กลับไปเว็บไซต์"
}
