import type { Language } from "@/components/language-provider"

export const uiCopy = {
  hi: {
    "ui.menu": "मेन्यू",
    "ui.theme": "रंग थीम बदलें",
    "ui.grid": "ग्रिड दृश्य",
    "ui.list": "सूची दृश्य",
    "ui.all": "सभी",
    "ui.project": "प्रोजेक्ट",
    "ui.projects": "प्रोजेक्ट",
    "ui.website": "वेबसाइट खोलें",
    "ui.instagram": "Instagram पर देखें",
    "ui.empty": "कोई प्रोजेक्ट नहीं मिला",
    "ui.retry": "दूसरी श्रेणी चुनें।",
    "ui.preview": "प्रीव्यू उपलब्ध नहीं है",
    "about.label": "मेरे बारे में और मेरा नेटवर्क"
  },
  th: {
    "ui.menu": "เมนู",
    "ui.theme": "เปลี่ยนธีมสี",
    "ui.grid": "มุมมองตาราง",
    "ui.list": "มุมมองรายการ",
    "ui.all": "ทั้งหมด",
    "ui.project": "โปรเจกต์",
    "ui.projects": "โปรเจกต์",
    "ui.website": "เข้าชมเว็บไซต์",
    "ui.instagram": "ดูบน Instagram",
    "ui.empty": "ไม่พบโปรเจกต์",
    "ui.retry": "เลือกหมวดหมู่อื่น",
    "ui.preview": "ไม่มีตัวอย่างให้ดู",
    "about.label": "เกี่ยวกับฉันและเครือข่าย"
  },
  uk: {
    "ui.menu": "Меню",
    "ui.theme": "Змінити колірну тему",
    "ui.grid": "Сітка",
    "ui.list": "Список",
    "ui.all": "Усі",
    "ui.project": "проєкт",
    "ui.projects": "проєкти",
    "ui.website": "Відвідати сайт",
    "ui.instagram": "Переглянути в Instagram",
    "ui.empty": "Проєктів не знайдено",
    "ui.retry": "Обери іншу категорію.",
    "ui.preview": "Перегляд недоступний",
    "about.label": "Про мене та мої контакти"
  },
  "de": {
    "ui.menu": "Menü",
    "ui.theme": "Farbschema wechseln",
    "ui.grid": "Rasteransicht",
    "ui.list": "Listenansicht",
    "ui.all": "Alle",
    "ui.project": "Projekt",
    "ui.projects": "Projekte",
    "ui.website": "Website besuchen",
    "ui.instagram": "Auf Instagram ansehen",
    "ui.empty": "Keine Projekte gefunden",
    "ui.retry": "Wähle eine andere Kategorie.",
    "ui.preview": "Vorschau nicht verfügbar",
    "about.label": "Über mich & mein Netzwerk"
  },
  "en": {
    "ui.menu": "Menu",
    "ui.theme": "Switch colour theme",
    "ui.grid": "Grid view",
    "ui.list": "List view",
    "ui.all": "All",
    "ui.project": "project",
    "ui.projects": "projects",
    "ui.website": "Visit website",
    "ui.instagram": "View on Instagram",
    "ui.empty": "No projects found",
    "ui.retry": "Choose another category.",
    "ui.preview": "Preview unavailable",
    "about.label": "About me & my network"
  },
  "fr": {
    "ui.menu": "Menu",
    "ui.theme": "Changer le thème",
    "ui.grid": "Vue en grille",
    "ui.list": "Vue en liste",
    "ui.all": "Tous",
    "ui.project": "projet",
    "ui.projects": "projets",
    "ui.website": "Visiter le site",
    "ui.instagram": "Voir sur Instagram",
    "ui.empty": "Aucun projet trouvé",
    "ui.retry": "Choisissez une autre catégorie.",
    "ui.preview": "Aperçu indisponible",
    "about.label": "À propos de moi et de mon réseau"
  },
  "es": {
    "ui.menu": "Menú",
    "ui.theme": "Cambiar tema",
    "ui.grid": "Vista de cuadrícula",
    "ui.list": "Vista de lista",
    "ui.all": "Todos",
    "ui.project": "proyecto",
    "ui.projects": "proyectos",
    "ui.website": "Visitar sitio",
    "ui.instagram": "Ver en Instagram",
    "ui.empty": "No hay proyectos",
    "ui.retry": "Elige otra categoría.",
    "ui.preview": "Vista previa no disponible",
    "about.label": "Sobre mí y mi red"
  },
  "it": {
    "ui.menu": "Menu",
    "ui.theme": "Cambia tema",
    "ui.grid": "Vista griglia",
    "ui.list": "Vista elenco",
    "ui.all": "Tutti",
    "ui.project": "progetto",
    "ui.projects": "progetti",
    "ui.website": "Visita il sito",
    "ui.instagram": "Vedi su Instagram",
    "ui.empty": "Nessun progetto",
    "ui.retry": "Scegli un'altra categoria.",
    "ui.preview": "Anteprima non disponibile",
    "about.label": "Su di me e sulla mia rete"
  },
  "pt": {
    "ui.menu": "Menu",
    "ui.theme": "Mudar tema",
    "ui.grid": "Vista em grelha",
    "ui.list": "Vista em lista",
    "ui.all": "Todos",
    "ui.project": "projeto",
    "ui.projects": "projetos",
    "ui.website": "Visitar site",
    "ui.instagram": "Ver no Instagram",
    "ui.empty": "Nenhum projeto",
    "ui.retry": "Escolha outra categoria.",
    "ui.preview": "Pré-visualização indisponível",
    "about.label": "Sobre mim e a minha rede"
  },
  "tr": {
    "ui.menu": "Menü",
    "ui.theme": "Temayı değiştir",
    "ui.grid": "Izgara görünümü",
    "ui.list": "Liste görünümü",
    "ui.all": "Tümü",
    "ui.project": "proje",
    "ui.projects": "proje",
    "ui.website": "Siteyi ziyaret et",
    "ui.instagram": "Instagram'da gör",
    "ui.empty": "Proje bulunamadı",
    "ui.retry": "Başka bir kategori seç.",
    "ui.preview": "Önizleme yok",
    "about.label": "Ben ve çevrem"
  },
  "sq": {
    "ui.menu": "Menuja",
    "ui.theme": "Ndrysho temën",
    "ui.grid": "Pamje rrjeti",
    "ui.list": "Pamje liste",
    "ui.all": "Të gjitha",
    "ui.project": "projekt",
    "ui.projects": "projekte",
    "ui.website": "Vizito faqen",
    "ui.instagram": "Shiko në Instagram",
    "ui.empty": "Nuk u gjetën projekte",
    "ui.retry": "Zgjidh një kategori tjetër.",
    "ui.preview": "Pamja paraprake mungon",
    "about.label": "Rreth meje dhe rrjetit tim"
  },
  "ru": {
    "ui.menu": "Меню",
    "ui.theme": "Сменить тему",
    "ui.grid": "Сетка",
    "ui.list": "Список",
    "ui.all": "Все",
    "ui.project": "проект",
    "ui.projects": "проектов",
    "ui.website": "Открыть сайт",
    "ui.instagram": "Открыть Instagram",
    "ui.empty": "Проекты не найдены",
    "ui.retry": "Выберите другую категорию.",
    "ui.preview": "Предпросмотр недоступен",
    "about.label": "Обо мне и моём окружении"
  },
  "el": {
    "ui.menu": "Μενού",
    "ui.theme": "Αλλαγή θέματος",
    "ui.grid": "Πλέγμα",
    "ui.list": "Λίστα",
    "ui.all": "Όλα",
    "ui.project": "έργο",
    "ui.projects": "έργα",
    "ui.website": "Δες την ιστοσελίδα",
    "ui.instagram": "Δες στο Instagram",
    "ui.empty": "Δεν βρέθηκαν έργα",
    "ui.retry": "Επίλεξε άλλη κατηγορία.",
    "ui.preview": "Η προεπισκόπηση δεν είναι διαθέσιμη",
    "about.label": "Εγώ και το δίκτυό μου"
  },
  "ar": {
    "ui.menu": "القائمة",
    "ui.theme": "تغيير المظهر",
    "ui.grid": "عرض شبكي",
    "ui.list": "عرض قائمة",
    "ui.all": "الكل",
    "ui.project": "مشروع",
    "ui.projects": "مشاريع",
    "ui.website": "زيارة الموقع",
    "ui.instagram": "عرض على إنستغرام",
    "ui.empty": "لم يتم العثور على مشاريع",
    "ui.retry": "اختر فئة أخرى.",
    "ui.preview": "المعاينة غير متاحة",
    "about.label": "عني وعن شبكة معارفي"
  },
  "zh": {
    "ui.menu": "菜单",
    "ui.theme": "切换主题",
    "ui.grid": "网格视图",
    "ui.list": "列表视图",
    "ui.all": "全部",
    "ui.project": "个项目",
    "ui.projects": "个项目",
    "ui.website": "访问网站",
    "ui.instagram": "在 Instagram 查看",
    "ui.empty": "暂无项目",
    "ui.retry": "请选择其他类别。",
    "ui.preview": "无法预览",
    "about.label": "关于我和我的人脉"
  }
} satisfies Record<Language, Record<string, string>>
